//
//  ExerciseUnitPivotSeeder.swift
//  fitness-app
//
//  Created by Dominic Kish on 1/26/26.
//
import GRDB
import Foundation

import Foundation

struct ExerciseUnitPivotSeeder {

    struct UnitAssignment {
        let units: [String]
    }

    static func seed(db: Database) throws {

        let count = try Int.fetchOne(
            db,
            sql: "SELECT COUNT(*) FROM exercise_unit_pivots"
        ) ?? 0
        guard count == 0 else { return }

        // Fetch exercises
        let exercises = try Row.fetchAll(db, sql: "SELECT id, name FROM exercises")
        let exerciseMap = Dictionary(
            uniqueKeysWithValues: exercises.map { ($0["name"] as String, $0["id"] as Int) }
        )

        // Fetch units
        let units = try Row.fetchAll(db, sql: "SELECT id, abbreviation AS name FROM units")
        let unitMap = Dictionary(
            uniqueKeysWithValues: units.map { ("\($0["name"] as String)", $0["id"] as Int) }
        )

        // ============================
        // Explicit, reasoned assignments
        // ============================
        let assignments: [String: UnitAssignment] = [
            "Plank": UnitAssignment(units: ["lbs", "kg"]),
            "Side Plank": UnitAssignment(units: ["lbs", "kg"]),
            "High Plank": UnitAssignment(units: ["lbs", "kg"]),
            "Low Plank": UnitAssignment(units: ["lbs", "kg"]),
            "Plank Shoulder Taps": UnitAssignment(units: ["lbs", "kg"]),
            "Plank Jacks": UnitAssignment(units: ["lbs", "kg"]),
            "Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Wide Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Narrow Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Diamond Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Incline Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Decline Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Pike Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Handstand Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Knee Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Archer Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Clap Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Hindu Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Narrow Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Wide Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Sumo Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Pulse Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Jump Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Box Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Wall Sit": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Leg Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Pistol Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Forward Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Walking Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Curtsy Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Jumping Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Side Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Step-Back Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Glute Bridge": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Leg Glute Bridge": UnitAssignment(units: ["lbs", "kg"]),
            "Hip Thrust (Bodyweight)": UnitAssignment(units: ["lbs", "kg"]),
            "Donkey Kicks": UnitAssignment(units: ["lbs", "kg"]),
            "Fire Hydrants": UnitAssignment(units: ["lbs", "kg"]),
            "Calf Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Leg Calf Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Burpees": UnitAssignment(units: ["lbs", "kg"]),
            "Half Burpee": UnitAssignment(units: ["lbs", "kg"]),
            "Bear Crawl": UnitAssignment(units: ["lbs", "kg"]),
            "Crab Walk": UnitAssignment(units: ["lbs", "kg"]),
            "Inchworm": UnitAssignment(units: ["lbs", "kg"]),
            "Jumping Jacks": UnitAssignment(units: ["lbs", "kg"]),
            "Star Jumps": UnitAssignment(units: ["lbs", "kg"]),
            "High Knees": UnitAssignment(units: ["lbs", "kg"]),
            "Butt Kicks": UnitAssignment(units: ["lbs", "kg"]),
            "Skater Jumps": UnitAssignment(units: ["lbs", "kg"]),
            "Tuck Jumps": UnitAssignment(units: ["lbs", "kg"]),
            "Broad Jumps": UnitAssignment(units: ["lbs", "kg"]),
            "Standing Long Jump": UnitAssignment(units: ["lbs", "kg"]),
            "Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Bicycle Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "V-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Toe Touches": UnitAssignment(units: ["lbs", "kg"]),
            "Flutter Kicks": UnitAssignment(units: ["lbs", "kg"]),
            "Scissor Kicks": UnitAssignment(units: ["lbs", "kg"]),
            "Leg Raises": UnitAssignment(units: ["lbs", "kg"]),
            "Hollow Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Superman Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Back Extension (Floor)": UnitAssignment(units: ["lbs", "kg"]),
            "Standing Oblique Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Russian Twist (Bodyweight)": UnitAssignment(units: ["lbs", "kg"]),
            "Seated Knee Tucks": UnitAssignment(units: ["lbs", "kg"]),
            "L-Sit": UnitAssignment(units: ["lbs", "kg"]),
            "Hanging Knee Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Hanging Leg Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Pull-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Chin-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Neutral Grip Pull-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Wide Grip Pull-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Australian Pull-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Negative Pull-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Isometric Pull-Up Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Dip (Bodyweight)": UnitAssignment(units: ["lbs", "kg"]),
            "Bench Dip": UnitAssignment(units: ["lbs", "kg"]),
            "Straight Arm Dip": UnitAssignment(units: ["lbs", "kg"]),
            
            "Dumbbell Bench Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Incline Bench Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Decline Bench Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Chest Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Incline Dumbbell Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Pullover": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Shoulder Press": UnitAssignment(units: ["lbs", "kg"]),
            "Seated Dumbbell Shoulder Press": UnitAssignment(units: ["lbs", "kg"]),
            "Arnold Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Front Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Lateral Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Upright Row": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Shrugs": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Bent-Over Row": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Dumbbell Row": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Renegade Row": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Romanian Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Sumo Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Goblet Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Front Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Split Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Bulgarian Split Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Reverse Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Walking Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Step-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Hip Thrust": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Glute Bridge": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Calf Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Seated Dumbbell Calf Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Bicep Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Alternating Dumbbell Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Hammer Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Cross-Body Hammer Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Concentration Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Incline Dumbbell Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Zottman Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Tricep Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Overhead Dumbbell Tricep Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Dumbbell Tricep Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Skull Crushers": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Kickbacks": UnitAssignment(units: ["lbs", "kg"]),
            "Close-Grip Dumbbell Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Wrist Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse Dumbbell Wrist Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Farmer's Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Dumbbell Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Suitcase Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Russian Twist": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Side Bend": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Woodchopper": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Sit-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell V-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Thruster": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Clean": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Clean and Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Snatch": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Dumbbell Snatch": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Push Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell High Pull": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Turkish Get-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Windmill": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Reverse Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Incline Dumbbell Reverse Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Cuban Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Around the World": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Floor Press": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Dumbbell Floor Press": UnitAssignment(units: ["lbs", "kg"]),
            "Dumbbell Pull-Over Crunch": UnitAssignment(units: ["lbs", "kg"]),
        
            "Barbell Back Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Front Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Box Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Pause Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Overhead Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Zercher Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Split Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Walking Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Reverse Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Conventional Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Sumo Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Romanian Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Stiff-Leg Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Deficit Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Rack Pull": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Hip Thrust": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Glute Bridge": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Bench Press": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Incline Bench Press": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Decline Bench Press": UnitAssignment(units: ["lbs", "kg"]),
            "Close-Grip Bench Press": UnitAssignment(units: ["lbs", "kg"]),
            "Paused Bench Press": UnitAssignment(units: ["lbs", "kg"]),
            "Spoto Press": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Floor Press": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Overhead Press": UnitAssignment(units: ["lbs", "kg"]),
            "Standing Military Press": UnitAssignment(units: ["lbs", "kg"]),
            "Seated Barbell Shoulder Press": UnitAssignment(units: ["lbs", "kg"]),
            "Push Press": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Split Jerk": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Push Jerk": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Upright Row": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell High Pull": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Bent-Over Row": UnitAssignment(units: ["lbs", "kg"]),
            "Pendlay Row": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Yates Row": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Meadows Row": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Shrug": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Curl": UnitAssignment(units: ["lbs", "kg"]),
            "EZ-Bar Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Wide-Grip Barbell Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse Barbell Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Drag Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Preacher Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Skull Crushers": UnitAssignment(units: ["lbs", "kg"]),
            "EZ-Bar Skull Crushers": UnitAssignment(units: ["lbs", "kg"]),
            "Close-Grip Barbell Press": UnitAssignment(units: ["lbs", "kg"]),
            "JM Press": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Tricep Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Wrist Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse Barbell Wrist Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Farmer’s Walk": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Rollout": UnitAssignment(units: ["lbs", "kg"]),
            "Standing Barbell Ab Rollout": UnitAssignment(units: ["lbs", "kg"]),
            "Landmine Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Landmine Press": UnitAssignment(units: ["lbs", "kg"]),
            "Landmine Row": UnitAssignment(units: ["lbs", "kg"]),
            "Landmine Rotation": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Clean": UnitAssignment(units: ["lbs", "kg"]),
            "Power Clean": UnitAssignment(units: ["lbs", "kg"]),
            "Hang Clean": UnitAssignment(units: ["lbs", "kg"]),
            "Clean and Jerk": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Snatch": UnitAssignment(units: ["lbs", "kg"]),
            "Power Snatch": UnitAssignment(units: ["lbs", "kg"]),
            "Hang Snatch": UnitAssignment(units: ["lbs", "kg"]),
            "Muscle Snatch": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Thruster": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Windmill": UnitAssignment(units: ["lbs", "kg"]),
            "Barbell Side Bend": UnitAssignment(units: ["lbs", "kg"]),
            
            "Leg Press Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Hack Squat Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Smith Machine Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Smith Machine Front Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Smith Machine Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Smith Machine Romanian Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Seated Leg Curl Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Lying Leg Curl Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Standing Leg Curl Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Leg Extension Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Hip Abductor Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Hip Adductor Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Standing Calf Raise Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Seated Calf Raise Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Chest Press Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Incline Chest Press Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Pec Deck Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Rear Delt Fly Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Seated Row Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Iso-Lateral Row Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Lat Pulldown": UnitAssignment(units: ["lbs", "kg"]),
            "Wide-Grip Lat Pulldown": UnitAssignment(units: ["lbs", "kg"]),
            "Close-Grip Lat Pulldown": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse-Grip Lat Pulldown": UnitAssignment(units: ["lbs", "kg"]),
            "Assisted Pull-Up Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Chest Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Low Cable Chest Fly": UnitAssignment(units: ["lbs", "kg"]),
            "High Cable Chest Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Crossover": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Shoulder Press": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Front Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Lateral Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Upright Row": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Face Pull": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Rear Delt Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Straight-Arm Pulldown": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Row": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Cable Row": UnitAssignment(units: ["lbs", "kg"]),
            "Cable High Row": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Shrugs": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Bicep Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Cable Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Hammer Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Preacher Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Tricep Pushdown": UnitAssignment(units: ["lbs", "kg"]),
            "Rope Tricep Pushdown": UnitAssignment(units: ["lbs", "kg"]),
            "V-Bar Tricep Pushdown": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Overhead Tricep Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Cable Tricep Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Kickback": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Woodchopper": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Pallof Press": UnitAssignment(units: ["lbs", "kg"]),
            "Machine Ab Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Captain’s Chair Knee Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Captain’s Chair Leg Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Back Extension Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse Hyper Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Glute Kickback Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Hip Thrust Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Assisted Dip Machine": UnitAssignment(units: ["lbs", "kg"]),
            "Machine Shoulder Press": UnitAssignment(units: ["lbs", "kg"]),
            "Machine Lateral Raise": UnitAssignment(units: ["lbs", "kg"]),
            "Machine Bicep Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Machine Tricep Extension": UnitAssignment(units: ["lbs", "kg"]),
            
            "Kettlebell Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Sumo Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Kettlebell Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Swing": UnitAssignment(units: ["lbs", "kg"]),
            "American Kettlebell Swing": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Kettlebell Swing": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Goblet Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Front Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Double Kettlebell Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Reverse Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Walking Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Step-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Clean": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Kettlebell Clean": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Clean and Press": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Press": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Kettlebell Press": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Push Press": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Jerk": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Snatch": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Kettlebell Snatch": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell High Pull": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Upright Row": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Bent-Over Row": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Kettlebell Row": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Floor Press": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Kettlebell Floor Press": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Chest Press": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Halo": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Around the Body": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Windmill": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Turkish Get-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Half Turkish Get-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Side Bend": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Russian Twist": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Sit-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell V-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Dead Bug": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Plank Drag": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Renegade Row": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Farmer’s Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Single-Arm Kettlebell Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Suitcase Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Overhead Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Double Kettlebell Front Rack Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell March": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Reverse Fly": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Hammer Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Tricep Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Skull Crushers": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Thruster": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Squat Clean": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Clean Squat Press": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Lateral Lunge": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Cossack Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Deadlift to High Pull": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Figure 8": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Figure 8 to Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Bottoms-Up Press": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Bottoms-Up Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Squat Press": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Single-Leg Deadlift": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Pistol Squat": UnitAssignment(units: ["lbs", "kg"]),
            "Kettlebell Jump Squat": UnitAssignment(units: ["lbs", "kg"]),
            
            "Running": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Jogging": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Sprinting": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Treadmill Running": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Incline Treadmill Walking": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Walking (Outdoor)": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Walking (Indoor)": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Walking (Treadmill)": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Power Walking": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Hiking": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Stair Climbing": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Stairmaster": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Elliptical Trainer": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Rowing Machine": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Air Bike": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Stationary Bike": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Spin Bike": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Assault Bike": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Ski Erg": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Jump Rope": UnitAssignment(units: ["none"]),
            "Double Unders": UnitAssignment(units: ["none"]),
            "Jump Rope High Knees": UnitAssignment(units: ["none"]),
            "Box Jumps": UnitAssignment(units: ["none"]),
            "Depth Jumps": UnitAssignment(units: ["none"]),
            "Plyometric Lunges": UnitAssignment(units: ["none"]),
            "Plyometric Push-Ups": UnitAssignment(units: ["none"]),
            "Wall Balls": UnitAssignment(units: ["none"]),
            "Medicine Ball Chest Pass": UnitAssignment(units: ["none"]),
            "Battle Ropes": UnitAssignment(units: ["none"]),
            "Alternating Battle Ropes": UnitAssignment(units: ["none"]),
            "Battle Rope Slams": UnitAssignment(units: ["none"]),
            "Sled Push": UnitAssignment(units: ["none"]),
            "Sled Pull": UnitAssignment(units: ["none"]),
            "Farmer’s Walk": UnitAssignment(units: ["lbs", "kg"]),
            "Yoke Carry": UnitAssignment(units: ["lbs", "kg"]),
            "Tire Flips": UnitAssignment(units: ["lbs", "kg"]),
            "Bear Crawl Sprint": UnitAssignment(units: ["none"]),
            "Shuttle Runs": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Agility Ladder Drills": UnitAssignment(units: ["none"]),
            "Cone Drills": UnitAssignment(units: ["none"]),
            "Suicides": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Fartlek Training": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Tempo Runs": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Interval Running": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Hill Sprints": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Swimming": UnitAssignment(units: ["none"]),
            "Freestyle Swimming": UnitAssignment(units: ["none"]),
            "Backstroke Swimming": UnitAssignment(units: ["none"]),
            "Breaststroke Swimming": UnitAssignment(units: ["none"]),
            "Butterfly Swimming": UnitAssignment(units: ["none"]),
            "Pool Walking": UnitAssignment(units: ["none"]),
            "Aqua Jogging": UnitAssignment(units: ["none"]),
            "Cycling": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Road Cycling": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Mountain Biking": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Indoor Cycling": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Rollerblading": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Rowing (On Water)": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Cross-Country Skiing": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Snowshoeing": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Jumping Lunges": UnitAssignment(units: ["none"]),
            "Shadow Boxing": UnitAssignment(units: ["none"]),
            "Heavy Bag Boxing": UnitAssignment(units: ["none"]),
            "HIIT Workout": UnitAssignment(units: ["none"]),
            "Tabata Workout": UnitAssignment(units: ["none"]),
            "AMRAP Workout": UnitAssignment(units: ["none"]),
            "EMOM Workout": UnitAssignment(units: ["none"]),
            "Strongman Conditioning": UnitAssignment(units: ["none"]),
            
            "Plank Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Side Plank Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Plank with Shoulder Taps": UnitAssignment(units: ["lbs", "kg"]),
            "Plank with Leg Lift": UnitAssignment(units: ["lbs", "kg"]),
            "Plank to Push-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse Plank": UnitAssignment(units: ["lbs", "kg"]),
            "Hollow Body Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Arch Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Dead Bug": UnitAssignment(units: ["lbs", "kg"]),
            "Bird Dog": UnitAssignment(units: ["lbs", "kg"]),
            "Toe Touch Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Heel Taps": UnitAssignment(units: ["lbs", "kg"]),
            "Sit-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Butterfly Sit-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Jackknife Sit-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Seated Leg Raises": UnitAssignment(units: ["lbs", "kg"]),
            "Lying Leg Raises": UnitAssignment(units: ["lbs", "kg"]),
            "Hanging Knee Raises": UnitAssignment(units: ["lbs", "kg"]),
            "Hanging Leg Raises": UnitAssignment(units: ["lbs", "kg"]),
            "Hanging Windshield Wipers": UnitAssignment(units: ["lbs", "kg"]),
            "Russian Twist": UnitAssignment(units: ["lbs", "kg"]),
            "Weighted Russian Twist": UnitAssignment(units: ["lbs", "kg"]),
            "Oblique Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Side Bend": UnitAssignment(units: ["lbs", "kg"]),
            "Cable Oblique Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Low to High Woodchopper": UnitAssignment(units: ["lbs", "kg"]),
            "High to Low Woodchopper": UnitAssignment(units: ["lbs", "kg"]),
            "Pallof Press": UnitAssignment(units: ["lbs", "kg"]),
            "Anti-Rotation Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Ab Wheel Rollout": UnitAssignment(units: ["lbs", "kg"]),
            "Kneeling Ab Rollout": UnitAssignment(units: ["lbs", "kg"]),
            "Standing Ab Rollout": UnitAssignment(units: ["lbs", "kg"]),
            "TRX Plank": UnitAssignment(units: ["lbs", "kg"]),
            "TRX Pike": UnitAssignment(units: ["lbs", "kg"]),
            "TRX Knee Tucks": UnitAssignment(units: ["lbs", "kg"]),
            "TRX Body Saw": UnitAssignment(units: ["lbs", "kg"]),
            "Medicine Ball Sit-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Medicine Ball V-Up": UnitAssignment(units: ["lbs", "kg"]),
            "Medicine Ball Russian Twist": UnitAssignment(units: ["lbs", "kg"]),
            "Medicine Ball Slams": UnitAssignment(units: ["lbs", "kg"]),
            "Medicine Ball Rotational Throw": UnitAssignment(units: ["lbs", "kg"]),
            "Stability Ball Crunch": UnitAssignment(units: ["lbs", "kg"]),
            "Stability Ball Pike": UnitAssignment(units: ["lbs", "kg"]),
            "Stability Ball Rollout": UnitAssignment(units: ["lbs", "kg"]),
            "Stability Ball Pass": UnitAssignment(units: ["lbs", "kg"]),
            "Swiss Ball Knee Tuck": UnitAssignment(units: ["lbs", "kg"]),
            "Back Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Roman Chair Back Extension": UnitAssignment(units: ["lbs", "kg"]),
            "Good Morning (Bodyweight)": UnitAssignment(units: ["lbs", "kg"]),
            "Reverse Hyperextension": UnitAssignment(units: ["lbs", "kg"]),
            "Jefferson Curl": UnitAssignment(units: ["lbs", "kg"]),
            "Farmer’s Carry Core Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Suitcase Carry Core Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Overhead Carry Core Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Turkish Get-Up (Core Focus)": UnitAssignment(units: ["lbs", "kg"]),
            "Bear Crawl Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Mountain Climbers": UnitAssignment(units: ["lbs", "kg"]),
            "Cross-Body Mountain Climbers": UnitAssignment(units: ["lbs", "kg"]),
            "Side Plank Hip Dips": UnitAssignment(units: ["lbs", "kg"]),
            "Copenhagen Plank": UnitAssignment(units: ["lbs", "kg"]),
            
            "Neck Flexion Stretch": UnitAssignment(units: ["none"]),
            "Neck Extension Stretch": UnitAssignment(units: ["none"]),
            "Neck Side Bend Stretch": UnitAssignment(units: ["none"]),
            "Neck Rotation Stretch": UnitAssignment(units: ["none"]),
            "Upper Trapezius Stretch": UnitAssignment(units: ["none"]),
            "Levator Scapulae Stretch": UnitAssignment(units: ["none"]),
            "Shoulder Rolls": UnitAssignment(units: ["none"]),
            "Arm Circles": UnitAssignment(units: ["none"]),
            "Cross-Body Shoulder Stretch": UnitAssignment(units: ["none"]),
            "Overhead Triceps Stretch": UnitAssignment(units: ["none"]),
            "Chest Opener Stretch": UnitAssignment(units: ["none"]),
            "Doorway Chest Stretch": UnitAssignment(units: ["none"]),
            "Shoulder Dislocates (Band)": UnitAssignment(units: ["none"]),
            "Scapular Push-Ups": UnitAssignment(units: ["lbs", "kg"]),
            "Scapular Pull-Ups": UnitAssignment(units: ["lbs", "kg"]),
            "Cat Cow Stretch": UnitAssignment(units: ["none"]),
            "Thoracic Spine Rotation": UnitAssignment(units: ["none"]),
            "Thoracic Extension on Foam Roller": UnitAssignment(units: ["none"]),
            "Child’s Pose": UnitAssignment(units: ["none"]),
            "Thread the Needle Stretch": UnitAssignment(units: ["none"]),
            "Cobra Stretch": UnitAssignment(units: ["none"]),
            "Upward Dog": UnitAssignment(units: ["none"]),
            "Downward Dog": UnitAssignment(units: ["none"]),
            "World’s Greatest Stretch": UnitAssignment(units: ["none"]),
            "Standing Forward Fold": UnitAssignment(units: ["none"]),
            "Seated Forward Fold": UnitAssignment(units: ["none"]),
            "Jefferson Curl (Mobility)": UnitAssignment(units: ["lbs", "kg"]),
            "Hip Flexor Stretch": UnitAssignment(units: ["none"]),
            "Half-Kneeling Hip Flexor Stretch": UnitAssignment(units: ["none"]),
            "Couch Stretch": UnitAssignment(units: ["none"]),
            "Figure Four Stretch": UnitAssignment(units: ["none"]),
            "Piriformis Stretch": UnitAssignment(units: ["none"]),
            "Glute Stretch": UnitAssignment(units: ["none"]),
            "Seated Spinal Twist": UnitAssignment(units: ["none"]),
            "Supine Spinal Twist": UnitAssignment(units: ["none"]),
            "90/90 Hip Stretch": UnitAssignment(units: ["none"]),
            "Hip CARs": UnitAssignment(units: ["none"]),
            "Ankle CARs": UnitAssignment(units: ["none"]),
            "Shoulder CARs": UnitAssignment(units: ["none"]),
            "Wrist CARs": UnitAssignment(units: ["none"]),
            "Deep Squat Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Goblet Squat Hold": UnitAssignment(units: ["lbs", "kg"]),
            "Adductor Rockbacks": UnitAssignment(units: ["none"]),
            "Hamstring Stretch (Standing)": UnitAssignment(units: ["none"]),
            "Hamstring Stretch (Seated)": UnitAssignment(units: ["none"]),
            "Hamstring Stretch (Lying)": UnitAssignment(units: ["none"]),
            "Calf Stretch (Wall)": UnitAssignment(units: ["none"]),
            "Soleus Stretch": UnitAssignment(units: ["none"]),
            "Quad Stretch (Standing)": UnitAssignment(units: ["none"]),
            "Quad Stretch (Side-Lying)": UnitAssignment(units: ["none"]),
            "Frog Stretch": UnitAssignment(units: ["none"]),
            "Butterfly Stretch": UnitAssignment(units: ["none"]),
            "Happy Baby Pose": UnitAssignment(units: ["none"]),
            "Pigeon Pose": UnitAssignment(units: ["none"]),
            "Lizard Pose": UnitAssignment(units: ["none"]),
            "Low Lunge Stretch": UnitAssignment(units: ["none"]),
            "Standing Side Bend Stretch": UnitAssignment(units: ["none"]),
            "Lat Stretch (Overhead)": UnitAssignment(units: ["none"]),
            "Lat Stretch (Bench)": UnitAssignment(units: ["none"]),
            "Foam Rolling Quads": UnitAssignment(units: ["none"]),
            "Foam Rolling Hamstrings": UnitAssignment(units: ["none"]),
            "Foam Rolling Glutes": UnitAssignment(units: ["none"]),
            "Foam Rolling IT Band": UnitAssignment(units: ["none"]),
            "Foam Rolling Calves": UnitAssignment(units: ["none"]),
            "Foam Rolling Upper Back": UnitAssignment(units: ["none"]),
            "Foam Rolling Lats": UnitAssignment(units: ["none"]),
            "Foam Rolling Chest": UnitAssignment(units: ["none"]),
            "Foam Rolling Shoulders": UnitAssignment(units: ["none"]),
            "Breathing Drill (Diaphragmatic)": UnitAssignment(units: ["none"]),
            "Box Breathing": UnitAssignment(units: ["none"]),
            "Crocodile Breathing": UnitAssignment(units: ["none"]),
            "Parasympathetic Breathing": UnitAssignment(units: ["none"]),
            "Guided Stretching Session": UnitAssignment(units: ["none"]),
            "Active Recovery Walk": UnitAssignment(units: ["mi", "yd", "km", "m"]),
            "Yoga Flow": UnitAssignment(units: ["none"]),
            "Restorative Yoga": UnitAssignment(units: ["none"]),
            "Mobility Flow": UnitAssignment(units: ["none"]),
            
            "Soccer": UnitAssignment(units: ["none"]),
            "Futsal": UnitAssignment(units: ["none"]),
            "Beach Soccer": UnitAssignment(units: ["none"]),
            "American Football": UnitAssignment(units: ["none"]),
            "Flag Football": UnitAssignment(units: ["none"]),
            "Arena Football": UnitAssignment(units: ["none"]),
            "Basketball": UnitAssignment(units: ["none"]),
            "Baseball": UnitAssignment(units: ["none"]),
            "Softball": UnitAssignment(units: ["none"]),
            "Fastpitch Softball": UnitAssignment(units: ["none"]),
            "Cricket": UnitAssignment(units: ["none"]),
            "Test Cricket": UnitAssignment(units: ["none"]),
            "One Day Cricket": UnitAssignment(units: ["none"]),
            "T20 Cricket": UnitAssignment(units: ["none"]),
            "Rugby Union": UnitAssignment(units: ["none"]),
            "Rugby League": UnitAssignment(units: ["none"]),
            "Rugby Sevens": UnitAssignment(units: ["none"]),
            "Ice Hockey": UnitAssignment(units: ["none"]),
            "Field Hockey": UnitAssignment(units: ["none"]),
            "Roller Hockey": UnitAssignment(units: ["none"]),
            "Lacrosse": UnitAssignment(units: ["none"]),
            "Box Lacrosse": UnitAssignment(units: ["none"]),
            "Tennis": UnitAssignment(units: ["none"]),
            "Doubles Tennis": UnitAssignment(units: ["none"]),
            "Table Tennis": UnitAssignment(units: ["none"]),
            "Badminton": UnitAssignment(units: ["none"]),
            "Squash": UnitAssignment(units: ["none"]),
            "Racquetball": UnitAssignment(units: ["none"]),
            "Padel": UnitAssignment(units: ["none"]),
            "Pickleball": UnitAssignment(units: ["none"]),
            "Volleyball (Indoor)": UnitAssignment(units: ["none"]),
            "Volleyball (Sand)": UnitAssignment(units: ["none"]),
            "Volleyball (Grass)": UnitAssignment(units: ["none"]),
            "Beach Handball": UnitAssignment(units: ["none"]),
            "Handball (Indoor)": UnitAssignment(units: ["none"]),
            "Water Polo": UnitAssignment(units: ["none"]),
            "Open Water Swimming": UnitAssignment(units: ["none"]),
            "Diving": UnitAssignment(units: ["none"]),
            "Surfing": UnitAssignment(units: ["none"]),
            "Bodyboarding": UnitAssignment(units: ["none"]),
            "Stand-Up Paddleboarding": UnitAssignment(units: ["none"]),
            "Rowing": UnitAssignment(units: ["none"]),
            "Kayaking": UnitAssignment(units: ["none"]),
            "Canoeing": UnitAssignment(units: ["none"]),
            "Sailing": UnitAssignment(units: ["none"]),
            "Cycling (Road)": UnitAssignment(units: ["none"]),
            "Cycling (Track)": UnitAssignment(units: ["none"]),
            "Cycling (Mountain)": UnitAssignment(units: ["none"]),
            "BMX Racing": UnitAssignment(units: ["none"]),
            "BMX Freestyle": UnitAssignment(units: ["none"]),
            "Triathlon": UnitAssignment(units: ["none"]),
            "Duathlon": UnitAssignment(units: ["none"]),
            "Athletics (Track & Field)": UnitAssignment(units: ["none"]),
            "Cross Country Running": UnitAssignment(units: ["none"]),
            "Marathon Running": UnitAssignment(units: ["none"]),
            "Trail Running": UnitAssignment(units: ["none"]),
            "Wrestling (Freestyle)": UnitAssignment(units: ["none"]),
            "Wrestling (Greco-Roman)": UnitAssignment(units: ["none"]),
            "Judo": UnitAssignment(units: ["none"]),
            "Brazilian Jiu-Jitsu": UnitAssignment(units: ["none"]),
            "Karate": UnitAssignment(units: ["none"]),
            "Taekwondo": UnitAssignment(units: ["none"]),
            "Boxing": UnitAssignment(units: ["none"]),
            "Kickboxing": UnitAssignment(units: ["none"]),
            "Muay Thai": UnitAssignment(units: ["none"]),
            "Mixed Martial Arts": UnitAssignment(units: ["none"]),
            "Golf": UnitAssignment(units: ["none"]),
            "Disc Golf": UnitAssignment(units: ["none"]),
            "Bowling": UnitAssignment(units: ["none"]),
            "Skateboarding": UnitAssignment(units: ["none"]),
            "Snowboarding": UnitAssignment(units: ["none"]),
            "Alpine Skiing": UnitAssignment(units: ["none"]),
            "Figure Skating": UnitAssignment(units: ["none"]),
            "Speed Skating": UnitAssignment(units: ["none"]),
            "Curling": UnitAssignment(units: ["none"]),
            
            "Mountain Pose (Tadasana)": UnitAssignment(units: ["none"]),
            "Downward-Facing Dog (Adho Mukha Svanasana)": UnitAssignment(units: ["none"]),
            "Upward-Facing Dog (Urdhva Mukha Svanasana)": UnitAssignment(units: ["none"]),
            "Plank Pose (Phalakasana)": UnitAssignment(units: ["none"]),
            "Chaturanga Dandasana": UnitAssignment(units: ["none"]),
            "Child’s Pose (Balasana)": UnitAssignment(units: ["none"]),
            "Cobra Pose (Bhujangasana)": UnitAssignment(units: ["none"]),
            "Warrior I (Virabhadrasana I)": UnitAssignment(units: ["none"]),
            "Warrior II (Virabhadrasana II)": UnitAssignment(units: ["none"]),
            "Warrior III (Virabhadrasana III)": UnitAssignment(units: ["none"]),
            "Triangle Pose (Trikonasana)": UnitAssignment(units: ["none"]),
            "Extended Side Angle Pose (Utthita Parsvakonasana)": UnitAssignment(units: ["none"]),
            "Tree Pose (Vrksasana)": UnitAssignment(units: ["none"]),
            "Chair Pose (Utkatasana)": UnitAssignment(units: ["none"]),
            "Bridge Pose (Setu Bandha Sarvangasana)": UnitAssignment(units: ["none"]),
            "Wheel Pose (Urdhva Dhanurasana)": UnitAssignment(units: ["none"]),
            "Seated Forward Fold (Paschimottanasana)": UnitAssignment(units: ["none"]),
            "Standing Forward Fold (Uttanasana)": UnitAssignment(units: ["none"]),
            "Half Forward Fold (Ardha Uttanasana)": UnitAssignment(units: ["none"]),
            "Easy Pose (Sukhasana)": UnitAssignment(units: ["none"]),
            "Lotus Pose (Padmasana)": UnitAssignment(units: ["none"]),
            "Half Lotus Pose (Ardha Padmasana)": UnitAssignment(units: ["none"]),
            "Bound Angle Pose (Baddha Konasana)": UnitAssignment(units: ["none"]),
            "Crescent Lunge (Anjaneyasana)": UnitAssignment(units: ["none"]),
            "Low Lunge (Ashwa Sanchalanasana)": UnitAssignment(units: ["none"]),
            "Pyramid Pose (Parsvottanasana)": UnitAssignment(units: ["none"]),
            "Garland Pose (Malasana)": UnitAssignment(units: ["none"]),
            "Boat Pose (Navasana)": UnitAssignment(units: ["none"]),
            "Cat Pose (Marjaryasana)": UnitAssignment(units: ["none"]),
            "Cow Pose (Bitilasana)": UnitAssignment(units: ["none"]),
            "Camel Pose (Ustrasana)": UnitAssignment(units: ["none"]),
            "Bow Pose (Dhanurasana)": UnitAssignment(units: ["none"]),
            "Fish Pose (Matsyasana)": UnitAssignment(units: ["none"]),
            "Corpse Pose (Savasana)": UnitAssignment(units: ["none"]),
            "Happy Baby Pose (Ananda Balasana)": UnitAssignment(units: ["none"]),
            "Supine Twist (Supta Matsyendrasana)": UnitAssignment(units: ["none"]),
            "Reclining Hand-to-Big-Toe Pose (Supta Padangusthasana)": UnitAssignment(units: ["none"]),
            "Eagle Pose (Garudasana)": UnitAssignment(units: ["none"]),
            "Half Moon Pose (Ardha Chandrasana)": UnitAssignment(units: ["none"]),
            "Side Plank Pose (Vasisthasana)": UnitAssignment(units: ["none"]),
            "Dolphin Pose (Ardha Pincha Mayurasana)": UnitAssignment(units: ["none"]),
            "Crow Pose (Bakasana)": UnitAssignment(units: ["none"]),
            "Pigeon Pose (Eka Pada Rajakapotasana)": UnitAssignment(units: ["none"]),
            "Lizard Pose (Utthan Pristhasana)": UnitAssignment(units: ["none"]),
            "Seated Twist (Ardha Matsyendrasana)": UnitAssignment(units: ["none"]),
            "Wide-Legged Forward Fold (Prasarita Padottanasana)": UnitAssignment(units: ["none"]),
            "Reverse Warrior (Viparita Virabhadrasana)": UnitAssignment(units: ["none"]),
            "Extended Hand-to-Big-Toe Pose (Utthita Hasta Padangusthasana)": UnitAssignment(units: ["none"]),
            "Fire Log Pose (Agnistambhasana)": UnitAssignment(units: ["none"]),
            "Thread the Needle Pose": UnitAssignment(units: ["none"]),
            "Knees-to-Chest Pose (Apanasana)": UnitAssignment(units: ["none"]),
            "Sphinx Pose (Salamba Bhujangasana)": UnitAssignment(units: ["none"]),
            "Hero Pose (Virasana)": UnitAssignment(units: ["none"]),
            "Revolved Triangle Pose (Parivrtta Trikonasana)": UnitAssignment(units: ["none"]),
            "Revolved Side Angle Pose (Parivrtta Parsvakonasana)": UnitAssignment(units: ["none"]),
            "Legs Up the Wall Pose (Viparita Karani)": UnitAssignment(units: ["none"]),
            "Four-Limbed Staff Pose (Chaturanga)": UnitAssignment(units: ["none"]),
            "Sun Salutation A (Surya Namaskar A)": UnitAssignment(units: ["none"]),
            "Sun Salutation B (Surya Namaskar B)": UnitAssignment(units: ["none"]),
            "Eight-Angle Pose (Astavakrasana)": UnitAssignment(units: ["none"]),
            "Shoulder Stand (Sarvangasana)": UnitAssignment(units: ["none"]),
            "Plow Pose (Halasana)": UnitAssignment(units: ["none"]),
            "Headstand (Sirsasana)": UnitAssignment(units: ["none"])
        ]

        // ============================
        // Insert pivot records
        // ============================
        for (exerciseName, assignment) in assignments {

            guard let exerciseId = exerciseMap[exerciseName] else {
                fatalError("❌ Exercise not found: \(exerciseName)")
            }

            try insert(db, exerciseId, assignment.units, unitMap)
        }

        print("🔗 Seeded exercise_unit_pivots table.")
    }
    
    private static func insert(
        _ db: Database,
        _ exerciseId: Int,
        _ unitNames: [String],
        _ unitMap: [String: Int]
    ) throws {

        for name in unitNames {
            guard let unitId = unitMap["\(name)"] else {
                fatalError("❌ Tag not found: \(name)")
            }

            try db.execute(
                sql: """
                INSERT INTO exercise_unit_pivots
                (exercise_id, unit_id, created_at, updated_at)
                VALUES (?, ?, ?, ?)
                """,
                arguments: [exerciseId, unitId, Date(), Date()]
            )
        }
    }

    
}
