//
//  ExerciseSeeder.swift
//  SimplyFitness
//
//  Created by Dominic Kish on 1/26/26.
//
import GRDB
import Foundation

struct ExerciseSeeder {
    static func seed(db: Database) throws {
        // Only seed if table is empty (Laravel-style)
        let count = try Int.fetchOne(db, sql: "SELECT COUNT(*) FROM exercises") ?? 0
        guard count == 0 else { return }

        // Preset exercises from your Laravel seeder
        let exercises: [[String: Any]] = [
            // Bodyweight & Calisthenics
            ["user_id": 0, "name": "Plank", "locked": true],
            ["user_id": 0, "name": "Side Plank", "locked": true],
            ["user_id": 0, "name": "High Plank", "locked": true],
            ["user_id": 0, "name": "Low Plank", "locked": true],
            ["user_id": 0, "name": "Plank Shoulder Taps", "locked": true],
            ["user_id": 0, "name": "Plank Jacks", "locked": true],
            ["user_id": 0, "name": "Push-Up", "locked": true],
            ["user_id": 0, "name": "Wide Push-Up", "locked": true],
            ["user_id": 0, "name": "Narrow Push-Up", "locked": true],
            ["user_id": 0, "name": "Diamond Push-Up", "locked": true],
            ["user_id": 0, "name": "Incline Push-Up", "locked": true],
            ["user_id": 0, "name": "Decline Push-Up", "locked": true],
            ["user_id": 0, "name": "Pike Push-Up", "locked": true],
            ["user_id": 0, "name": "Handstand Push-Up", "locked": true],
            ["user_id": 0, "name": "Knee Push-Up", "locked": true],
            ["user_id": 0, "name": "Archer Push-Up", "locked": true],
            ["user_id": 0, "name": "Clap Push-Up", "locked": true],
            ["user_id": 0, "name": "Hindu Push-Up", "locked": true],
            ["user_id": 0, "name": "Squat", "locked": true],
            ["user_id": 0, "name": "Narrow Squat", "locked": true],
            ["user_id": 0, "name": "Wide Squat", "locked": true],
            ["user_id": 0, "name": "Sumo Squat", "locked": true],
            ["user_id": 0, "name": "Pulse Squat", "locked": true],
            ["user_id": 0, "name": "Jump Squat", "locked": true],
            ["user_id": 0, "name": "Box Squat", "locked": true],
            ["user_id": 0, "name": "Wall Sit", "locked": true],
            ["user_id": 0, "name": "Single-Leg Squat", "locked": true],
            ["user_id": 0, "name": "Pistol Squat", "locked": true],
            ["user_id": 0, "name": "Reverse Lunge", "locked": true],
            ["user_id": 0, "name": "Forward Lunge", "locked": true],
            ["user_id": 0, "name": "Walking Lunge", "locked": true],
            ["user_id": 0, "name": "Curtsy Lunge", "locked": true],
            ["user_id": 0, "name": "Jumping Lunge", "locked": true],
            ["user_id": 0, "name": "Side Lunge", "locked": true],
            ["user_id": 0, "name": "Step-Back Lunge", "locked": true],
            ["user_id": 0, "name": "Glute Bridge", "locked": true],
            ["user_id": 0, "name": "Single-Leg Glute Bridge", "locked": true],
            ["user_id": 0, "name": "Hip Thrust (Bodyweight)", "locked": true],
            ["user_id": 0, "name": "Donkey Kicks", "locked": true],
            ["user_id": 0, "name": "Fire Hydrants", "locked": true],
            ["user_id": 0, "name": "Calf Raise", "locked": true],
            ["user_id": 0, "name": "Single-Leg Calf Raise", "locked": true],
            ["user_id": 0, "name": "Burpees", "locked": true],
            ["user_id": 0, "name": "Half Burpee", "locked": true],
            ["user_id": 0, "name": "Bear Crawl", "locked": true],
            ["user_id": 0, "name": "Crab Walk", "locked": true],
            ["user_id": 0, "name": "Inchworm", "locked": true],
            ["user_id": 0, "name": "Jumping Jacks", "locked": true],
            ["user_id": 0, "name": "Star Jumps", "locked": true],
            ["user_id": 0, "name": "High Knees", "locked": true],
            ["user_id": 0, "name": "Butt Kicks", "locked": true],
            ["user_id": 0, "name": "Skater Jumps", "locked": true],
            ["user_id": 0, "name": "Tuck Jumps", "locked": true],
            ["user_id": 0, "name": "Broad Jumps", "locked": true],
            ["user_id": 0, "name": "Standing Long Jump", "locked": true],
            ["user_id": 0, "name": "Crunch", "locked": true],
            ["user_id": 0, "name": "Bicycle Crunch", "locked": true],
            ["user_id": 0, "name": "Toe Touches", "locked": true],
            ["user_id": 0, "name": "Leg Raises", "locked": true],
            ["user_id": 0, "name": "Hollow Hold", "locked": true],
            ["user_id": 0, "name": "Superman Hold", "locked": true],
            ["user_id": 0, "name": "Back Extension (Floor)", "locked": true],
            ["user_id": 0, "name": "Bird Dog", "locked": true],
            ["user_id": 0, "name": "Standing Oblique Crunch", "locked": true],
            ["user_id": 0, "name": "Russian Twist (Bodyweight)", "locked": true],
            ["user_id": 0, "name": "Seated Knee Tucks", "locked": true],
            ["user_id": 0, "name": "L-Sit", "locked": true],
            ["user_id": 0, "name": "Hanging Knee Raise", "locked": true],
            ["user_id": 0, "name": "Hanging Leg Raise", "locked": true],
            ["user_id": 0, "name": "Pull-Up", "locked": true],
            ["user_id": 0, "name": "Chin-Up", "locked": true],
            ["user_id": 0, "name": "Neutral Grip Pull-Up", "locked": true],
            ["user_id": 0, "name": "Wide Grip Pull-Up", "locked": true],
            ["user_id": 0, "name": "Australian Pull-Up", "locked": true],
            ["user_id": 0, "name": "Negative Pull-Up", "locked": true],
            ["user_id": 0, "name": "Isometric Pull-Up Hold", "locked": true],
            ["user_id": 0, "name": "Dip (Bodyweight)", "locked": true],
            ["user_id": 0, "name": "Bench Dip", "locked": true],
            ["user_id": 0, "name": "Straight Arm Dip", "locked": true],
            
            // Dumbell Exercises
            ["user_id": 0, "name": "Dumbbell Bench Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell Incline Bench Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell Decline Bench Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell Chest Fly", "locked": true],
            ["user_id": 0, "name": "Incline Dumbbell Fly", "locked": true],
            ["user_id": 0, "name": "Dumbbell Pullover", "locked": true],
            ["user_id": 0, "name": "Dumbbell Shoulder Press", "locked": true],
            ["user_id": 0, "name": "Seated Dumbbell Shoulder Press", "locked": true],
            ["user_id": 0, "name": "Arnold Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell Front Raise", "locked": true],
            ["user_id": 0, "name": "Dumbbell Lateral Raise", "locked": true],
            ["user_id": 0, "name": "Dumbbell Upright Row", "locked": true],
            ["user_id": 0, "name": "Dumbbell Shrugs", "locked": true],
            ["user_id": 0, "name": "Dumbbell Bent-Over Row", "locked": true],
            ["user_id": 0, "name": "Single-Arm Dumbbell Row", "locked": true],
            ["user_id": 0, "name": "Dumbbell Renegade Row", "locked": true],
            ["user_id": 0, "name": "Dumbbell Deadlift", "locked": true],
            ["user_id": 0, "name": "Dumbbell Romanian Deadlift", "locked": true],
            ["user_id": 0, "name": "Dumbbell Sumo Deadlift", "locked": true],
            ["user_id": 0, "name": "Dumbbell Squat", "locked": true],
            ["user_id": 0, "name": "Goblet Squat", "locked": true],
            ["user_id": 0, "name": "Dumbbell Front Squat", "locked": true],
            ["user_id": 0, "name": "Dumbbell Split Squat", "locked": true],
            ["user_id": 0, "name": "Dumbbell Bulgarian Split Squat", "locked": true],
            ["user_id": 0, "name": "Dumbbell Reverse Lunge", "locked": true],
            ["user_id": 0, "name": "Dumbbell Walking Lunge", "locked": true],
            ["user_id": 0, "name": "Dumbbell Step-Up", "locked": true],
            ["user_id": 0, "name": "Dumbbell Hip Thrust", "locked": true],
            ["user_id": 0, "name": "Dumbbell Glute Bridge", "locked": true],
            ["user_id": 0, "name": "Dumbbell Calf Raise", "locked": true],
            ["user_id": 0, "name": "Seated Dumbbell Calf Raise", "locked": true],
            ["user_id": 0, "name": "Dumbbell Bicep Curl", "locked": true],
            ["user_id": 0, "name": "Alternating Dumbbell Curl", "locked": true],
            ["user_id": 0, "name": "Hammer Curl", "locked": true],
            ["user_id": 0, "name": "Cross-Body Hammer Curl", "locked": true],
            ["user_id": 0, "name": "Concentration Curl", "locked": true],
            ["user_id": 0, "name": "Incline Dumbbell Curl", "locked": true],
            ["user_id": 0, "name": "Zottman Curl", "locked": true],
            ["user_id": 0, "name": "Dumbbell Tricep Extension", "locked": true],
            ["user_id": 0, "name": "Overhead Dumbbell Tricep Extension", "locked": true],
            ["user_id": 0, "name": "Single-Arm Dumbbell Tricep Extension", "locked": true],
            ["user_id": 0, "name": "Dumbbell Skull Crushers", "locked": true],
            ["user_id": 0, "name": "Dumbbell Kickbacks", "locked": true],
            ["user_id": 0, "name": "Close-Grip Dumbbell Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell Wrist Curl", "locked": true],
            ["user_id": 0, "name": "Reverse Dumbbell Wrist Curl", "locked": true],
            ["user_id": 0, "name": "Dumbbell Farmer's Carry", "locked": true],
            ["user_id": 0, "name": "Single-Arm Dumbbell Carry", "locked": true],
            ["user_id": 0, "name": "Dumbbell Suitcase Carry", "locked": true],
            ["user_id": 0, "name": "Dumbbell Russian Twist", "locked": true],
            ["user_id": 0, "name": "Dumbbell Side Bend", "locked": true],
            ["user_id": 0, "name": "Dumbbell Woodchopper", "locked": true],
            ["user_id": 0, "name": "Dumbbell Sit-Up", "locked": true],
            ["user_id": 0, "name": "Dumbbell V-Up", "locked": true],
            ["user_id": 0, "name": "Dumbbell Thruster", "locked": true],
            ["user_id": 0, "name": "Dumbbell Clean", "locked": true],
            ["user_id": 0, "name": "Dumbbell Clean and Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell Snatch", "locked": true],
            ["user_id": 0, "name": "Single-Arm Dumbbell Snatch", "locked": true],
            ["user_id": 0, "name": "Dumbbell Push Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell High Pull", "locked": true],
            ["user_id": 0, "name": "Dumbbell Turkish Get-Up", "locked": true],
            ["user_id": 0, "name": "Dumbbell Windmill", "locked": true],
            ["user_id": 0, "name": "Dumbbell Reverse Fly", "locked": true],
            ["user_id": 0, "name": "Incline Dumbbell Reverse Fly", "locked": true],
            ["user_id": 0, "name": "Dumbbell Cuban Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell Around the World", "locked": true],
            ["user_id": 0, "name": "Dumbbell Floor Press", "locked": true],
            ["user_id": 0, "name": "Single-Arm Dumbbell Floor Press", "locked": true],
            ["user_id": 0, "name": "Dumbbell Pull-Over Crunch", "locked": true],
            
            // Barbell
            ["user_id": 0, "name": "Barbell Back Squat", "locked": true],
            ["user_id": 0, "name": "Barbell Front Squat", "locked": true],
            ["user_id": 0, "name": "Barbell Box Squat", "locked": true],
            ["user_id": 0, "name": "Barbell Pause Squat", "locked": true],
            ["user_id": 0, "name": "Barbell Overhead Squat", "locked": true],
            ["user_id": 0, "name": "Barbell Zercher Squat", "locked": true],
            ["user_id": 0, "name": "Barbell Split Squat", "locked": true],
            ["user_id": 0, "name": "Barbell Lunge", "locked": true],
            ["user_id": 0, "name": "Barbell Walking Lunge", "locked": true],
            ["user_id": 0, "name": "Barbell Reverse Lunge", "locked": true],
            ["user_id": 0, "name": "Barbell Deadlift", "locked": true],
            ["user_id": 0, "name": "Conventional Deadlift", "locked": true],
            ["user_id": 0, "name": "Sumo Deadlift", "locked": true],
            ["user_id": 0, "name": "Barbell Romanian Deadlift", "locked": true],
            ["user_id": 0, "name": "Barbell Stiff-Leg Deadlift", "locked": true],
            ["user_id": 0, "name": "Deficit Deadlift", "locked": true],
            ["user_id": 0, "name": "Rack Pull", "locked": true],
            ["user_id": 0, "name": "Barbell Hip Thrust", "locked": true],
            ["user_id": 0, "name": "Barbell Glute Bridge", "locked": true],
            ["user_id": 0, "name": "Barbell Bench Press", "locked": true],
            ["user_id": 0, "name": "Barbell Incline Bench Press", "locked": true],
            ["user_id": 0, "name": "Barbell Decline Bench Press", "locked": true],
            ["user_id": 0, "name": "Close-Grip Bench Press", "locked": true],
            ["user_id": 0, "name": "Paused Bench Press", "locked": true],
            ["user_id": 0, "name": "Spoto Press", "locked": true],
            ["user_id": 0, "name": "Barbell Floor Press", "locked": true],
            ["user_id": 0, "name": "Barbell Overhead Press", "locked": true],
            ["user_id": 0, "name": "Standing Military Press", "locked": true],
            ["user_id": 0, "name": "Seated Barbell Shoulder Press", "locked": true],
            ["user_id": 0, "name": "Push Press", "locked": true],
            ["user_id": 0, "name": "Barbell Split Jerk", "locked": true],
            ["user_id": 0, "name": "Barbell Push Jerk", "locked": true],
            ["user_id": 0, "name": "Barbell Upright Row", "locked": true],
            ["user_id": 0, "name": "Barbell High Pull", "locked": true],
            ["user_id": 0, "name": "Barbell Bent-Over Row", "locked": true],
            ["user_id": 0, "name": "Pendlay Row", "locked": true],
            ["user_id": 0, "name": "Barbell Yates Row", "locked": true],
            ["user_id": 0, "name": "Barbell Meadows Row", "locked": true],
            ["user_id": 0, "name": "Barbell Shrug", "locked": true],
            ["user_id": 0, "name": "Barbell Curl", "locked": true],
            ["user_id": 0, "name": "EZ-Bar Curl", "locked": true],
            ["user_id": 0, "name": "Wide-Grip Barbell Curl", "locked": true],
            ["user_id": 0, "name": "Reverse Barbell Curl", "locked": true],
            ["user_id": 0, "name": "Barbell Drag Curl", "locked": true],
            ["user_id": 0, "name": "Barbell Preacher Curl", "locked": true],
            ["user_id": 0, "name": "Barbell Skull Crushers", "locked": true],
            ["user_id": 0, "name": "EZ-Bar Skull Crushers", "locked": true],
            ["user_id": 0, "name": "Close-Grip Barbell Press", "locked": true],
            ["user_id": 0, "name": "JM Press", "locked": true],
            ["user_id": 0, "name": "Barbell Tricep Extension", "locked": true],
            ["user_id": 0, "name": "Barbell Wrist Curl", "locked": true],
            ["user_id": 0, "name": "Reverse Barbell Wrist Curl", "locked": true],
            ["user_id": 0, "name": "Barbell Farmer’s Walk", "locked": true],
            ["user_id": 0, "name": "Barbell Rollout", "locked": true],
            ["user_id": 0, "name": "Standing Barbell Ab Rollout", "locked": true],
            ["user_id": 0, "name": "Landmine Squat", "locked": true],
            ["user_id": 0, "name": "Landmine Press", "locked": true],
            ["user_id": 0, "name": "Landmine Row", "locked": true],
            ["user_id": 0, "name": "Landmine Rotation", "locked": true],
            ["user_id": 0, "name": "Barbell Clean", "locked": true],
            ["user_id": 0, "name": "Power Clean", "locked": true],
            ["user_id": 0, "name": "Hang Clean", "locked": true],
            ["user_id": 0, "name": "Clean and Jerk", "locked": true],
            ["user_id": 0, "name": "Barbell Snatch", "locked": true],
            ["user_id": 0, "name": "Power Snatch", "locked": true],
            ["user_id": 0, "name": "Hang Snatch", "locked": true],
            ["user_id": 0, "name": "Muscle Snatch", "locked": true],
            ["user_id": 0, "name": "Barbell Thruster", "locked": true],
            ["user_id": 0, "name": "Barbell Windmill", "locked": true],
            ["user_id": 0, "name": "Barbell Side Bend", "locked": true],
            
            // Machine / Cable
            ["user_id": 0, "name": "Leg Press Machine", "locked": true],
            ["user_id": 0, "name": "Hack Squat Machine", "locked": true],
            ["user_id": 0, "name": "Smith Machine Squat", "locked": true],
            ["user_id": 0, "name": "Smith Machine Front Squat", "locked": true],
            ["user_id": 0, "name": "Smith Machine Lunge", "locked": true],
            ["user_id": 0, "name": "Smith Machine Romanian Deadlift", "locked": true],
            ["user_id": 0, "name": "Seated Leg Curl Machine", "locked": true],
            ["user_id": 0, "name": "Lying Leg Curl Machine", "locked": true],
            ["user_id": 0, "name": "Standing Leg Curl Machine", "locked": true],
            ["user_id": 0, "name": "Leg Extension Machine", "locked": true],
            ["user_id": 0, "name": "Hip Abductor Machine", "locked": true],
            ["user_id": 0, "name": "Hip Adductor Machine", "locked": true],
            ["user_id": 0, "name": "Standing Calf Raise Machine", "locked": true],
            ["user_id": 0, "name": "Seated Calf Raise Machine", "locked": true],
            ["user_id": 0, "name": "Chest Press Machine", "locked": true],
            ["user_id": 0, "name": "Incline Chest Press Machine", "locked": true],
            ["user_id": 0, "name": "Pec Deck Machine", "locked": true],
            ["user_id": 0, "name": "Rear Delt Fly Machine", "locked": true],
            ["user_id": 0, "name": "Seated Row Machine", "locked": true],
            ["user_id": 0, "name": "Iso-Lateral Row Machine", "locked": true],
            ["user_id": 0, "name": "Lat Pulldown", "locked": true],
            ["user_id": 0, "name": "Wide-Grip Lat Pulldown", "locked": true],
            ["user_id": 0, "name": "Close-Grip Lat Pulldown", "locked": true],
            ["user_id": 0, "name": "Reverse-Grip Lat Pulldown", "locked": true],
            ["user_id": 0, "name": "Assisted Pull-Up Machine", "locked": true],
            ["user_id": 0, "name": "Cable Chest Fly", "locked": true],
            ["user_id": 0, "name": "Low Cable Chest Fly", "locked": true],
            ["user_id": 0, "name": "High Cable Chest Fly", "locked": true],
            ["user_id": 0, "name": "Cable Crossover", "locked": true],
            ["user_id": 0, "name": "Cable Shoulder Press", "locked": true],
            ["user_id": 0, "name": "Cable Front Raise", "locked": true],
            ["user_id": 0, "name": "Cable Lateral Raise", "locked": true],
            ["user_id": 0, "name": "Cable Upright Row", "locked": true],
            ["user_id": 0, "name": "Cable Face Pull", "locked": true],
            ["user_id": 0, "name": "Cable Rear Delt Fly", "locked": true],
            ["user_id": 0, "name": "Cable Straight-Arm Pulldown", "locked": true],
            ["user_id": 0, "name": "Cable Row", "locked": true],
            ["user_id": 0, "name": "Single-Arm Cable Row", "locked": true],
            ["user_id": 0, "name": "Cable High Row", "locked": true],
            ["user_id": 0, "name": "Cable Shrugs", "locked": true],
            ["user_id": 0, "name": "Cable Bicep Curl", "locked": true],
            ["user_id": 0, "name": "Single-Arm Cable Curl", "locked": true],
            ["user_id": 0, "name": "Cable Hammer Curl", "locked": true],
            ["user_id": 0, "name": "Cable Preacher Curl", "locked": true],
            ["user_id": 0, "name": "Cable Tricep Pushdown", "locked": true],
            ["user_id": 0, "name": "Rope Tricep Pushdown", "locked": true],
            ["user_id": 0, "name": "V-Bar Tricep Pushdown", "locked": true],
            ["user_id": 0, "name": "Cable Overhead Tricep Extension", "locked": true],
            ["user_id": 0, "name": "Single-Arm Cable Tricep Extension", "locked": true],
            ["user_id": 0, "name": "Cable Kickback", "locked": true],
            ["user_id": 0, "name": "Cable Woodchopper", "locked": true],
            ["user_id": 0, "name": "Cable Pallof Press", "locked": true],
            ["user_id": 0, "name": "Machine Ab Crunch", "locked": true],
            ["user_id": 0, "name": "Captain’s Chair Knee Raise", "locked": true],
            ["user_id": 0, "name": "Captain’s Chair Leg Raise", "locked": true],
            ["user_id": 0, "name": "Back Extension Machine", "locked": true],
            ["user_id": 0, "name": "Reverse Hyper Machine", "locked": true],
            ["user_id": 0, "name": "Glute Kickback Machine", "locked": true],
            ["user_id": 0, "name": "Hip Thrust Machine", "locked": true],
            ["user_id": 0, "name": "Assisted Dip Machine", "locked": true],
            ["user_id": 0, "name": "Machine Shoulder Press", "locked": true],
            ["user_id": 0, "name": "Machine Lateral Raise", "locked": true],
            ["user_id": 0, "name": "Machine Bicep Curl", "locked": true],
            ["user_id": 0, "name": "Machine Tricep Extension", "locked": true],

            
            // Kettlebell
            ["user_id": 0, "name": "Kettlebell Deadlift", "locked": true],
            ["user_id": 0, "name": "Kettlebell Sumo Deadlift", "locked": true],
            ["user_id": 0, "name": "Single-Arm Kettlebell Deadlift", "locked": true],
            ["user_id": 0, "name": "Kettlebell Swing", "locked": true],
            ["user_id": 0, "name": "American Kettlebell Swing", "locked": true],
            ["user_id": 0, "name": "Single-Arm Kettlebell Swing", "locked": true],
            ["user_id": 0, "name": "Kettlebell Goblet Squat", "locked": true],
            ["user_id": 0, "name": "Kettlebell Front Squat", "locked": true],
            ["user_id": 0, "name": "Double Kettlebell Squat", "locked": true],
            ["user_id": 0, "name": "Kettlebell Lunge", "locked": true],
            ["user_id": 0, "name": "Kettlebell Reverse Lunge", "locked": true],
            ["user_id": 0, "name": "Kettlebell Walking Lunge", "locked": true],
            ["user_id": 0, "name": "Kettlebell Step-Up", "locked": true],
            ["user_id": 0, "name": "Kettlebell Clean", "locked": true],
            ["user_id": 0, "name": "Single-Arm Kettlebell Clean", "locked": true],
            ["user_id": 0, "name": "Kettlebell Clean and Press", "locked": true],
            ["user_id": 0, "name": "Kettlebell Press", "locked": true],
            ["user_id": 0, "name": "Single-Arm Kettlebell Press", "locked": true],
            ["user_id": 0, "name": "Kettlebell Push Press", "locked": true],
            ["user_id": 0, "name": "Kettlebell Jerk", "locked": true],
            ["user_id": 0, "name": "Kettlebell Snatch", "locked": true],
            ["user_id": 0, "name": "Single-Arm Kettlebell Snatch", "locked": true],
            ["user_id": 0, "name": "Kettlebell High Pull", "locked": true],
            ["user_id": 0, "name": "Kettlebell Upright Row", "locked": true],
            ["user_id": 0, "name": "Kettlebell Bent-Over Row", "locked": true],
            ["user_id": 0, "name": "Single-Arm Kettlebell Row", "locked": true],
            ["user_id": 0, "name": "Kettlebell Floor Press", "locked": true],
            ["user_id": 0, "name": "Single-Arm Kettlebell Floor Press", "locked": true],
            ["user_id": 0, "name": "Kettlebell Chest Press", "locked": true],
            ["user_id": 0, "name": "Kettlebell Fly", "locked": true],
            ["user_id": 0, "name": "Kettlebell Halo", "locked": true],
            ["user_id": 0, "name": "Kettlebell Around the Body", "locked": true],
            ["user_id": 0, "name": "Kettlebell Windmill", "locked": true],
            ["user_id": 0, "name": "Kettlebell Turkish Get-Up", "locked": true],
            ["user_id": 0, "name": "Half Turkish Get-Up", "locked": true],
            ["user_id": 0, "name": "Kettlebell Side Bend", "locked": true],
            ["user_id": 0, "name": "Kettlebell Russian Twist", "locked": true],
            ["user_id": 0, "name": "Kettlebell Sit-Up", "locked": true],
            ["user_id": 0, "name": "Kettlebell V-Up", "locked": true],
            ["user_id": 0, "name": "Kettlebell Dead Bug", "locked": true],
            ["user_id": 0, "name": "Kettlebell Plank Drag", "locked": true],
            ["user_id": 0, "name": "Kettlebell Renegade Row", "locked": true],
            ["user_id": 0, "name": "Kettlebell Farmer’s Carry", "locked": true],
            ["user_id": 0, "name": "Single-Arm Kettlebell Carry", "locked": true],
            ["user_id": 0, "name": "Kettlebell Suitcase Carry", "locked": true],
            ["user_id": 0, "name": "Kettlebell Overhead Carry", "locked": true],
            ["user_id": 0, "name": "Double Kettlebell Front Rack Carry", "locked": true],
            ["user_id": 0, "name": "Kettlebell March", "locked": true],
            ["user_id": 0, "name": "Kettlebell Reverse Fly", "locked": true],
            ["user_id": 0, "name": "Kettlebell Curl", "locked": true],
            ["user_id": 0, "name": "Kettlebell Hammer Curl", "locked": true],
            ["user_id": 0, "name": "Kettlebell Tricep Extension", "locked": true],
            ["user_id": 0, "name": "Kettlebell Skull Crushers", "locked": true],
            ["user_id": 0, "name": "Kettlebell Thruster", "locked": true],
            ["user_id": 0, "name": "Kettlebell Squat Clean", "locked": true],
            ["user_id": 0, "name": "Kettlebell Clean Squat Press", "locked": true],
            ["user_id": 0, "name": "Kettlebell Lateral Lunge", "locked": true],
            ["user_id": 0, "name": "Kettlebell Cossack Squat", "locked": true],
            ["user_id": 0, "name": "Kettlebell Deadlift to High Pull", "locked": true],
            ["user_id": 0, "name": "Kettlebell Figure 8", "locked": true],
            ["user_id": 0, "name": "Kettlebell Figure 8 to Hold", "locked": true],
            ["user_id": 0, "name": "Kettlebell Bottoms-Up Press", "locked": true],
            ["user_id": 0, "name": "Kettlebell Bottoms-Up Carry", "locked": true],
            ["user_id": 0, "name": "Kettlebell Squat Press", "locked": true],
            ["user_id": 0, "name": "Kettlebell Single-Leg Deadlift", "locked": true],
            ["user_id": 0, "name": "Kettlebell Pistol Squat", "locked": true],
            ["user_id": 0, "name": "Kettlebell Jump Squat", "locked": true],

            
            // Cardio & Conditioning
            ["user_id": 0, "name": "Running", "locked": true],
            ["user_id": 0, "name": "Jogging", "locked": true],
            ["user_id": 0, "name": "Sprinting", "locked": true],
            ["user_id": 0, "name": "Treadmill Running", "locked": true],
            ["user_id": 0, "name": "Incline Treadmill Walking", "locked": true],
            ["user_id": 0, "name": "Walking (Outdoor)", "locked": true],
            ["user_id": 0, "name": "Walking (Indoor)", "locked": true],
            ["user_id": 0, "name": "Walking (Treadmill)", "locked": true],
            ["user_id": 0, "name": "Power Walking", "locked": true],
            ["user_id": 0, "name": "Hiking", "locked": true],
            ["user_id": 0, "name": "Stair Climbing", "locked": true],
            ["user_id": 0, "name": "Stairmaster", "locked": true],
            ["user_id": 0, "name": "Elliptical Trainer", "locked": true],
            ["user_id": 0, "name": "Rowing Machine", "locked": true],
            ["user_id": 0, "name": "Air Bike", "locked": true],
            ["user_id": 0, "name": "Stationary Bike", "locked": true],
            ["user_id": 0, "name": "Spin Bike", "locked": true],
            ["user_id": 0, "name": "Assault Bike", "locked": true],
            ["user_id": 0, "name": "Ski Erg", "locked": true],
            ["user_id": 0, "name": "Jump Rope", "locked": true],
            ["user_id": 0, "name": "Double Unders", "locked": true],
            ["user_id": 0, "name": "Jump Rope High Knees", "locked": true],
            ["user_id": 0, "name": "Box Jumps", "locked": true],
            ["user_id": 0, "name": "Depth Jumps", "locked": true],
            ["user_id": 0, "name": "Plyometric Lunges", "locked": true],
            ["user_id": 0, "name": "Plyometric Push-Ups", "locked": true],
            ["user_id": 0, "name": "Wall Balls", "locked": true],
            ["user_id": 0, "name": "Medicine Ball Chest Pass", "locked": true],
            ["user_id": 0, "name": "Battle Ropes", "locked": true],
            ["user_id": 0, "name": "Alternating Battle Ropes", "locked": true],
            ["user_id": 0, "name": "Battle Rope Slams", "locked": true],
            ["user_id": 0, "name": "Sled Push", "locked": true],
            ["user_id": 0, "name": "Sled Pull", "locked": true],
            ["user_id": 0, "name": "Farmer’s Walk", "locked": true],
            ["user_id": 0, "name": "Yoke Carry", "locked": true],
            ["user_id": 0, "name": "Tire Flips", "locked": true],
            ["user_id": 0, "name": "Bear Crawl Sprint", "locked": true],
            ["user_id": 0, "name": "Shuttle Runs", "locked": true],
            ["user_id": 0, "name": "Agility Ladder Drills", "locked": true],
            ["user_id": 0, "name": "Cone Drills", "locked": true],
            ["user_id": 0, "name": "Suicides", "locked": true],
            ["user_id": 0, "name": "Fartlek Training", "locked": true],
            ["user_id": 0, "name": "Tempo Runs", "locked": true],
            ["user_id": 0, "name": "Interval Running", "locked": true],
            ["user_id": 0, "name": "Hill Sprints", "locked": true],
            ["user_id": 0, "name": "Swimming", "locked": true],
            ["user_id": 0, "name": "Freestyle Swimming", "locked": true],
            ["user_id": 0, "name": "Backstroke Swimming", "locked": true],
            ["user_id": 0, "name": "Breaststroke Swimming", "locked": true],
            ["user_id": 0, "name": "Butterfly Swimming", "locked": true],
            ["user_id": 0, "name": "Pool Walking", "locked": true],
            ["user_id": 0, "name": "Aqua Jogging", "locked": true],
            ["user_id": 0, "name": "Cycling", "locked": true],
            ["user_id": 0, "name": "Road Cycling", "locked": true],
            ["user_id": 0, "name": "Mountain Biking", "locked": true],
            ["user_id": 0, "name": "Indoor Cycling", "locked": true],
            ["user_id": 0, "name": "Rollerblading", "locked": true],
            ["user_id": 0, "name": "Rowing (On Water)", "locked": true],
            ["user_id": 0, "name": "Kayaking", "locked": true],
            ["user_id": 0, "name": "Canoeing", "locked": true],
            ["user_id": 0, "name": "Snowshoeing", "locked": true],
            ["user_id": 0, "name": "Jumping Lunges", "locked": true],
            ["user_id": 0, "name": "Shadow Boxing", "locked": true],
            ["user_id": 0, "name": "Heavy Bag Boxing", "locked": true],
            ["user_id": 0, "name": "HIIT Workout", "locked": true],
            ["user_id": 0, "name": "Tabata Workout", "locked": true],
            ["user_id": 0, "name": "AMRAP Workout", "locked": true],
            ["user_id": 0, "name": "EMOM Workout", "locked": true],
            ["user_id": 0, "name": "Strongman Conditioning", "locked": true],

            // Core / Abs
            ["user_id": 0, "name": "Plank Hold", "locked": true],
            ["user_id": 0, "name": "Side Plank Hold", "locked": true],
            ["user_id": 0, "name": "Plank with Shoulder Taps", "locked": true],
            ["user_id": 0, "name": "Plank with Leg Lift", "locked": true],
            ["user_id": 0, "name": "Plank to Push-Up", "locked": true],
            ["user_id": 0, "name": "Reverse Plank", "locked": true],
            ["user_id": 0, "name": "Hollow Body Hold", "locked": true],
            ["user_id": 0, "name": "Arch Hold", "locked": true],
            ["user_id": 0, "name": "Dead Bug", "locked": true],
            ["user_id": 0, "name": "Reverse Crunch", "locked": true],
            ["user_id": 0, "name": "Toe Touch Crunch", "locked": true],
            ["user_id": 0, "name": "Heel Taps", "locked": true],
            ["user_id": 0, "name": "Sit-Up", "locked": true],
            ["user_id": 0, "name": "Butterfly Sit-Up", "locked": true],
            ["user_id": 0, "name": "V-Up", "locked": true],
            ["user_id": 0, "name": "Jackknife Sit-Up", "locked": true],
            ["user_id": 0, "name": "Seated Leg Raises", "locked": true],
            ["user_id": 0, "name": "Lying Leg Raises", "locked": true],
            ["user_id": 0, "name": "Hanging Knee Raises", "locked": true],
            ["user_id": 0, "name": "Hanging Leg Raises", "locked": true],
            ["user_id": 0, "name": "Hanging Windshield Wipers", "locked": true],
            ["user_id": 0, "name": "Flutter Kicks", "locked": true],
            ["user_id": 0, "name": "Scissor Kicks", "locked": true],
            ["user_id": 0, "name": "Russian Twist", "locked": true],
            ["user_id": 0, "name": "Weighted Russian Twist", "locked": true],
            ["user_id": 0, "name": "Oblique Crunch", "locked": true],
            ["user_id": 0, "name": "Side Bend", "locked": true],
            ["user_id": 0, "name": "Cable Crunch", "locked": true],
            ["user_id": 0, "name": "Cable Oblique Crunch", "locked": true],
            ["user_id": 0, "name": "Low to High Woodchopper", "locked": true],
            ["user_id": 0, "name": "High to Low Woodchopper", "locked": true],
            ["user_id": 0, "name": "Pallof Press", "locked": true],
            ["user_id": 0, "name": "Anti-Rotation Hold", "locked": true],
            ["user_id": 0, "name": "Ab Wheel Rollout", "locked": true],
            ["user_id": 0, "name": "Kneeling Ab Rollout", "locked": true],
            ["user_id": 0, "name": "Standing Ab Rollout", "locked": true],
            ["user_id": 0, "name": "TRX Plank", "locked": true],
            ["user_id": 0, "name": "TRX Pike", "locked": true],
            ["user_id": 0, "name": "TRX Knee Tucks", "locked": true],
            ["user_id": 0, "name": "TRX Body Saw", "locked": true],
            ["user_id": 0, "name": "Medicine Ball Sit-Up", "locked": true],
            ["user_id": 0, "name": "Medicine Ball V-Up", "locked": true],
            ["user_id": 0, "name": "Medicine Ball Russian Twist", "locked": true],
            ["user_id": 0, "name": "Medicine Ball Slams", "locked": true],
            ["user_id": 0, "name": "Medicine Ball Rotational Throw", "locked": true],
            ["user_id": 0, "name": "Stability Ball Crunch", "locked": true],
            ["user_id": 0, "name": "Stability Ball Pike", "locked": true],
            ["user_id": 0, "name": "Stability Ball Rollout", "locked": true],
            ["user_id": 0, "name": "Stability Ball Pass", "locked": true],
            ["user_id": 0, "name": "Swiss Ball Knee Tuck", "locked": true],
            ["user_id": 0, "name": "Back Extension", "locked": true],
            ["user_id": 0, "name": "Roman Chair Back Extension", "locked": true],
            ["user_id": 0, "name": "Good Morning (Bodyweight)", "locked": true],
            ["user_id": 0, "name": "Reverse Hyperextension", "locked": true],
            ["user_id": 0, "name": "Jefferson Curl", "locked": true],
            ["user_id": 0, "name": "Farmer’s Carry Core Hold", "locked": true],
            ["user_id": 0, "name": "Suitcase Carry Core Hold", "locked": true],
            ["user_id": 0, "name": "Overhead Carry Core Hold", "locked": true],
            ["user_id": 0, "name": "Turkish Get-Up (Core Focus)", "locked": true],
            ["user_id": 0, "name": "Bear Crawl Hold", "locked": true],
            ["user_id": 0, "name": "Mountain Climbers", "locked": true],
            ["user_id": 0, "name": "Cross-Body Mountain Climbers", "locked": true],
            ["user_id": 0, "name": "Side Plank Hip Dips", "locked": true],
            ["user_id": 0, "name": "Copenhagen Plank", "locked": true],

            // Mobility / Stretch / Recovery
            ["user_id": 0, "name": "Neck Flexion Stretch", "locked": true],
            ["user_id": 0, "name": "Neck Extension Stretch", "locked": true],
            ["user_id": 0, "name": "Neck Side Bend Stretch", "locked": true],
            ["user_id": 0, "name": "Neck Rotation Stretch", "locked": true],
            ["user_id": 0, "name": "Upper Trapezius Stretch", "locked": true],
            ["user_id": 0, "name": "Levator Scapulae Stretch", "locked": true],
            ["user_id": 0, "name": "Shoulder Rolls", "locked": true],
            ["user_id": 0, "name": "Arm Circles", "locked": true],
            ["user_id": 0, "name": "Cross-Body Shoulder Stretch", "locked": true],
            ["user_id": 0, "name": "Overhead Triceps Stretch", "locked": true],
            ["user_id": 0, "name": "Chest Opener Stretch", "locked": true],
            ["user_id": 0, "name": "Doorway Chest Stretch", "locked": true],
            ["user_id": 0, "name": "Shoulder Dislocates (Band)", "locked": true],
            ["user_id": 0, "name": "Scapular Push-Ups", "locked": true],
            ["user_id": 0, "name": "Scapular Pull-Ups", "locked": true],
            ["user_id": 0, "name": "Cat Cow Stretch", "locked": true],
            ["user_id": 0, "name": "Thoracic Spine Rotation", "locked": true],
            ["user_id": 0, "name": "Thoracic Extension on Foam Roller", "locked": true],
            ["user_id": 0, "name": "Child’s Pose", "locked": true],
            ["user_id": 0, "name": "Thread the Needle Stretch", "locked": true],
            ["user_id": 0, "name": "Cobra Stretch", "locked": true],
            ["user_id": 0, "name": "Upward Dog", "locked": true],
            ["user_id": 0, "name": "Downward Dog", "locked": true],
            ["user_id": 0, "name": "World’s Greatest Stretch", "locked": true],
            ["user_id": 0, "name": "Standing Forward Fold", "locked": true],
            ["user_id": 0, "name": "Seated Forward Fold", "locked": true],
            ["user_id": 0, "name": "Jefferson Curl (Mobility)", "locked": true],
            ["user_id": 0, "name": "Hip Flexor Stretch", "locked": true],
            ["user_id": 0, "name": "Half-Kneeling Hip Flexor Stretch", "locked": true],
            ["user_id": 0, "name": "Couch Stretch", "locked": true],
            ["user_id": 0, "name": "Figure Four Stretch", "locked": true],
            ["user_id": 0, "name": "Piriformis Stretch", "locked": true],
            ["user_id": 0, "name": "Glute Stretch", "locked": true],
            ["user_id": 0, "name": "Seated Spinal Twist", "locked": true],
            ["user_id": 0, "name": "Supine Spinal Twist", "locked": true],
            ["user_id": 0, "name": "90/90 Hip Stretch", "locked": true],
            ["user_id": 0, "name": "Hip CARs", "locked": true],
            ["user_id": 0, "name": "Ankle CARs", "locked": true],
            ["user_id": 0, "name": "Shoulder CARs", "locked": true],
            ["user_id": 0, "name": "Wrist CARs", "locked": true],
            ["user_id": 0, "name": "Deep Squat Hold", "locked": true],
            ["user_id": 0, "name": "Goblet Squat Hold", "locked": true],
            ["user_id": 0, "name": "Adductor Rockbacks", "locked": true],
            ["user_id": 0, "name": "Hamstring Stretch (Standing)", "locked": true],
            ["user_id": 0, "name": "Hamstring Stretch (Seated)", "locked": true],
            ["user_id": 0, "name": "Hamstring Stretch (Lying)", "locked": true],
            ["user_id": 0, "name": "Calf Stretch (Wall)", "locked": true],
            ["user_id": 0, "name": "Soleus Stretch", "locked": true],
            ["user_id": 0, "name": "Quad Stretch (Standing)", "locked": true],
            ["user_id": 0, "name": "Quad Stretch (Side-Lying)", "locked": true],
            ["user_id": 0, "name": "Frog Stretch", "locked": true],
            ["user_id": 0, "name": "Butterfly Stretch", "locked": true],
            ["user_id": 0, "name": "Happy Baby Pose", "locked": true],
            ["user_id": 0, "name": "Pigeon Pose", "locked": true],
            ["user_id": 0, "name": "Lizard Pose", "locked": true],
            ["user_id": 0, "name": "Low Lunge Stretch", "locked": true],
            ["user_id": 0, "name": "Standing Side Bend Stretch", "locked": true],
            ["user_id": 0, "name": "Lat Stretch (Overhead)", "locked": true],
            ["user_id": 0, "name": "Lat Stretch (Bench)", "locked": true],
            ["user_id": 0, "name": "Foam Rolling Quads", "locked": true],
            ["user_id": 0, "name": "Foam Rolling Hamstrings", "locked": true],
            ["user_id": 0, "name": "Foam Rolling Glutes", "locked": true],
            ["user_id": 0, "name": "Foam Rolling IT Band", "locked": true],
            ["user_id": 0, "name": "Foam Rolling Calves", "locked": true],
            ["user_id": 0, "name": "Foam Rolling Upper Back", "locked": true],
            ["user_id": 0, "name": "Foam Rolling Lats", "locked": true],
            ["user_id": 0, "name": "Foam Rolling Chest", "locked": true],
            ["user_id": 0, "name": "Foam Rolling Shoulders", "locked": true],
            ["user_id": 0, "name": "Breathing Drill (Diaphragmatic)", "locked": true],
            ["user_id": 0, "name": "Box Breathing", "locked": true],
            ["user_id": 0, "name": "Crocodile Breathing", "locked": true],
            ["user_id": 0, "name": "Parasympathetic Breathing", "locked": true],
            ["user_id": 0, "name": "Guided Stretching Session", "locked": true],
            ["user_id": 0, "name": "Active Recovery Walk", "locked": true],
            ["user_id": 0, "name": "Yoga Flow", "locked": true],
            ["user_id": 0, "name": "Restorative Yoga", "locked": true],
            ["user_id": 0, "name": "Mobility Flow", "locked": true],
            
            // Sports
            ["user_id": 0, "name": "Soccer", "locked": true],
            ["user_id": 0, "name": "Futsal", "locked": true],
            ["user_id": 0, "name": "Beach Soccer", "locked": true],
            ["user_id": 0, "name": "American Football", "locked": true],
            ["user_id": 0, "name": "Flag Football", "locked": true],
            ["user_id": 0, "name": "Arena Football", "locked": true],
            ["user_id": 0, "name": "Basketball", "locked": true],
            ["user_id": 0, "name": "Baseball", "locked": true],
            ["user_id": 0, "name": "Softball", "locked": true],
            ["user_id": 0, "name": "Fastpitch Softball", "locked": true],
            ["user_id": 0, "name": "Cricket", "locked": true],
            ["user_id": 0, "name": "Test Cricket", "locked": true],
            ["user_id": 0, "name": "One Day Cricket", "locked": true],
            ["user_id": 0, "name": "T20 Cricket", "locked": true],
            ["user_id": 0, "name": "Rugby Union", "locked": true],
            ["user_id": 0, "name": "Rugby League", "locked": true],
            ["user_id": 0, "name": "Rugby Sevens", "locked": true],
            ["user_id": 0, "name": "Ice Hockey", "locked": true],
            ["user_id": 0, "name": "Field Hockey", "locked": true],
            ["user_id": 0, "name": "Roller Hockey", "locked": true],
            ["user_id": 0, "name": "Lacrosse", "locked": true],
            ["user_id": 0, "name": "Box Lacrosse", "locked": true],
            ["user_id": 0, "name": "Tennis", "locked": true],
            ["user_id": 0, "name": "Doubles Tennis", "locked": true],
            ["user_id": 0, "name": "Table Tennis", "locked": true],
            ["user_id": 0, "name": "Badminton", "locked": true],
            ["user_id": 0, "name": "Squash", "locked": true],
            ["user_id": 0, "name": "Racquetball", "locked": true],
            ["user_id": 0, "name": "Padel", "locked": true],
            ["user_id": 0, "name": "Pickleball", "locked": true],
            ["user_id": 0, "name": "Volleyball (Indoor)", "locked": true],
            ["user_id": 0, "name": "Volleyball (Sand)", "locked": true],
            ["user_id": 0, "name": "Volleyball (Grass)", "locked": true],
            ["user_id": 0, "name": "Beach Handball", "locked": true],
            ["user_id": 0, "name": "Handball (Indoor)", "locked": true],
            ["user_id": 0, "name": "Water Polo", "locked": true],
            ["user_id": 0, "name": "Open Water Swimming", "locked": true],
            ["user_id": 0, "name": "Diving", "locked": true],
            ["user_id": 0, "name": "Surfing", "locked": true],
            ["user_id": 0, "name": "Bodyboarding", "locked": true],
            ["user_id": 0, "name": "Stand-Up Paddleboarding", "locked": true],
            ["user_id": 0, "name": "Rowing", "locked": true],
            ["user_id": 0, "name": "Sailing", "locked": true],
            ["user_id": 0, "name": "Cycling (Road)", "locked": true],
            ["user_id": 0, "name": "Cycling (Track)", "locked": true],
            ["user_id": 0, "name": "Cycling (Mountain)", "locked": true],
            ["user_id": 0, "name": "BMX Racing", "locked": true],
            ["user_id": 0, "name": "BMX Freestyle", "locked": true],
            ["user_id": 0, "name": "Triathlon", "locked": true],
            ["user_id": 0, "name": "Duathlon", "locked": true],
            ["user_id": 0, "name": "Athletics (Track & Field)", "locked": true],
            ["user_id": 0, "name": "Cross Country Running", "locked": true],
            ["user_id": 0, "name": "Marathon Running", "locked": true],
            ["user_id": 0, "name": "Trail Running", "locked": true],
            ["user_id": 0, "name": "Wrestling (Freestyle)", "locked": true],
            ["user_id": 0, "name": "Wrestling (Greco-Roman)", "locked": true],
            ["user_id": 0, "name": "Judo", "locked": true],
            ["user_id": 0, "name": "Brazilian Jiu-Jitsu", "locked": true],
            ["user_id": 0, "name": "Karate", "locked": true],
            ["user_id": 0, "name": "Taekwondo", "locked": true],
            ["user_id": 0, "name": "Boxing", "locked": true],
            ["user_id": 0, "name": "Kickboxing", "locked": true],
            ["user_id": 0, "name": "Muay Thai", "locked": true],
            ["user_id": 0, "name": "Mixed Martial Arts", "locked": true],
            ["user_id": 0, "name": "Golf", "locked": true],
            ["user_id": 0, "name": "Disc Golf", "locked": true],
            ["user_id": 0, "name": "Bowling", "locked": true],
            ["user_id": 0, "name": "Skateboarding", "locked": true],
            ["user_id": 0, "name": "Snowboarding", "locked": true],
            ["user_id": 0, "name": "Alpine Skiing", "locked": true],
            ["user_id": 0, "name": "Cross-Country Skiing", "locked": true],
            ["user_id": 0, "name": "Figure Skating", "locked": true],
            ["user_id": 0, "name": "Speed Skating", "locked": true],
            ["user_id": 0, "name": "Curling", "locked": true],
            
            // Yoga
            ["user_id": 0, "name": "Mountain Pose (Tadasana)", "locked": true],
            ["user_id": 0, "name": "Downward-Facing Dog (Adho Mukha Svanasana)", "locked": true],
            ["user_id": 0, "name": "Upward-Facing Dog (Urdhva Mukha Svanasana)", "locked": true],
            ["user_id": 0, "name": "Plank Pose (Phalakasana)", "locked": true],
            ["user_id": 0, "name": "Chaturanga Dandasana", "locked": true],
            ["user_id": 0, "name": "Child’s Pose (Balasana)", "locked": true],
            ["user_id": 0, "name": "Cobra Pose (Bhujangasana)", "locked": true],
            ["user_id": 0, "name": "Warrior I (Virabhadrasana I)", "locked": true],
            ["user_id": 0, "name": "Warrior II (Virabhadrasana II)", "locked": true],
            ["user_id": 0, "name": "Warrior III (Virabhadrasana III)", "locked": true],
            ["user_id": 0, "name": "Triangle Pose (Trikonasana)", "locked": true],
            ["user_id": 0, "name": "Extended Side Angle Pose (Utthita Parsvakonasana)", "locked": true],
            ["user_id": 0, "name": "Tree Pose (Vrksasana)", "locked": true],
            ["user_id": 0, "name": "Chair Pose (Utkatasana)", "locked": true],
            ["user_id": 0, "name": "Bridge Pose (Setu Bandha Sarvangasana)", "locked": true],
            ["user_id": 0, "name": "Wheel Pose (Urdhva Dhanurasana)", "locked": true],
            ["user_id": 0, "name": "Seated Forward Fold (Paschimottanasana)", "locked": true],
            ["user_id": 0, "name": "Standing Forward Fold (Uttanasana)", "locked": true],
            ["user_id": 0, "name": "Half Forward Fold (Ardha Uttanasana)", "locked": true],
            ["user_id": 0, "name": "Easy Pose (Sukhasana)", "locked": true],
            ["user_id": 0, "name": "Lotus Pose (Padmasana)", "locked": true],
            ["user_id": 0, "name": "Half Lotus Pose (Ardha Padmasana)", "locked": true],
            ["user_id": 0, "name": "Bound Angle Pose (Baddha Konasana)", "locked": true],
            ["user_id": 0, "name": "Crescent Lunge (Anjaneyasana)", "locked": true],
            ["user_id": 0, "name": "Low Lunge (Ashwa Sanchalanasana)", "locked": true],
            ["user_id": 0, "name": "Pyramid Pose (Parsvottanasana)", "locked": true],
            ["user_id": 0, "name": "Garland Pose (Malasana)", "locked": true],
            ["user_id": 0, "name": "Boat Pose (Navasana)", "locked": true],
            ["user_id": 0, "name": "Cat Pose (Marjaryasana)", "locked": true],
            ["user_id": 0, "name": "Cow Pose (Bitilasana)", "locked": true],
            ["user_id": 0, "name": "Camel Pose (Ustrasana)", "locked": true],
            ["user_id": 0, "name": "Bow Pose (Dhanurasana)", "locked": true],
            ["user_id": 0, "name": "Fish Pose (Matsyasana)", "locked": true],
            ["user_id": 0, "name": "Corpse Pose (Savasana)", "locked": true],
            ["user_id": 0, "name": "Happy Baby Pose (Ananda Balasana)", "locked": true],
            ["user_id": 0, "name": "Supine Twist (Supta Matsyendrasana)", "locked": true],
            ["user_id": 0, "name": "Reclining Hand-to-Big-Toe Pose (Supta Padangusthasana)", "locked": true],
            ["user_id": 0, "name": "Eagle Pose (Garudasana)", "locked": true],
            ["user_id": 0, "name": "Half Moon Pose (Ardha Chandrasana)", "locked": true],
            ["user_id": 0, "name": "Side Plank Pose (Vasisthasana)", "locked": true],
            ["user_id": 0, "name": "Dolphin Pose (Ardha Pincha Mayurasana)", "locked": true],
            ["user_id": 0, "name": "Crow Pose (Bakasana)", "locked": true],
            ["user_id": 0, "name": "Pigeon Pose (Eka Pada Rajakapotasana)", "locked": true],
            ["user_id": 0, "name": "Lizard Pose (Utthan Pristhasana)", "locked": true],
            ["user_id": 0, "name": "Seated Twist (Ardha Matsyendrasana)", "locked": true],
            ["user_id": 0, "name": "Wide-Legged Forward Fold (Prasarita Padottanasana)", "locked": true],
            ["user_id": 0, "name": "Reverse Warrior (Viparita Virabhadrasana)", "locked": true],
            ["user_id": 0, "name": "Extended Hand-to-Big-Toe Pose (Utthita Hasta Padangusthasana)", "locked": true],
            ["user_id": 0, "name": "Fire Log Pose (Agnistambhasana)", "locked": true],
            ["user_id": 0, "name": "Thread the Needle Pose", "locked": true],
            ["user_id": 0, "name": "Knees-to-Chest Pose (Apanasana)", "locked": true],
            ["user_id": 0, "name": "Sphinx Pose (Salamba Bhujangasana)", "locked": true],
            ["user_id": 0, "name": "Hero Pose (Virasana)", "locked": true],
            ["user_id": 0, "name": "Revolved Triangle Pose (Parivrtta Trikonasana)", "locked": true],
            ["user_id": 0, "name": "Revolved Side Angle Pose (Parivrtta Parsvakonasana)", "locked": true],
            ["user_id": 0, "name": "Legs Up the Wall Pose (Viparita Karani)", "locked": true],
            ["user_id": 0, "name": "Four-Limbed Staff Pose (Chaturanga)", "locked": true],
            ["user_id": 0, "name": "Sun Salutation A (Surya Namaskar A)", "locked": true],
            ["user_id": 0, "name": "Sun Salutation B (Surya Namaskar B)", "locked": true],
            ["user_id": 0, "name": "Eight-Angle Pose (Astavakrasana)", "locked": true],
            ["user_id": 0, "name": "Shoulder Stand (Sarvangasana)", "locked": true],
            ["user_id": 0, "name": "Plow Pose (Halasana)", "locked": true],
            ["user_id": 0, "name": "Headstand (Sirsasana)", "locked": true]



        ]

        // Insert exercises
        for exercise in exercises {
            try db.execute(
                sql: """
                INSERT INTO exercises (user_id, name, locked, created_at, updated_at)
                VALUES (:user_id, :name, :locked, :created_at, :updated_at)
                """,
                arguments: [
                    "user_id": exercise["user_id"] as! Int,
                    "name": exercise["name"] as! String,
                    "locked": exercise["locked"] as! Bool,
                    "created_at": Date(),
                    "updated_at": Date()
                ]
            )
        }

        print("📝 Seeded exercises table with \(exercises.count) records.")
    }
}

