//
//  ExerciseTagPivotSeeder.swift
//  fitness-app
//
//  Created by Dominic Kish on 1/26/26.
//
import GRDB
import Foundation

struct ExerciseTagPivotSeeder {

    struct TagAssignment {
        let groups: [String]
        let categories: [String]
        let workouts: [String]
    }

    static func seed(db: Database) throws {

        let count = try Int.fetchOne(
            db,
            sql: "SELECT COUNT(*) FROM exercise_tag_pivots"
        ) ?? 0
        guard count == 0 else { return }

        // Fetch exercises
        let exercises = try Row.fetchAll(db, sql: "SELECT id, name FROM exercises")
        let exerciseMap = Dictionary(
            uniqueKeysWithValues: exercises.map { ($0["name"] as String, $0["id"] as Int) }
        )

        // Fetch tags
        let tags = try Row.fetchAll(db, sql: "SELECT id, name, type FROM exercise_tags")
        let tagMap = Dictionary(
            uniqueKeysWithValues: tags.map { ("\($0["type"] as String)|\($0["name"] as String)", $0["id"] as Int) }
        )

        // ============================
        // Explicit, reasoned assignments
        // ============================
        let assignments: [String: TagAssignment] = [
            // MARK: - Planks
            "Plank": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Side Plank": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "High Plank": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body"]),
            "Low Plank": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body"]),
            "Plank Shoulder Taps": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Full Body"]),
            "Plank Jacks": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["HIIT", "Cardio"]),

            // MARK: - Push-Ups
            "Push-Up": TagAssignment(groups: ["Chest", "Arms"], categories: ["Bodyweight"], workouts: ["Push", "Upper Body"]),
            "Wide Push-Up": TagAssignment(groups: ["Chest"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Narrow Push-Up": TagAssignment(groups: ["Triceps"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Diamond Push-Up": TagAssignment(groups: ["Triceps", "Chest"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Incline Push-Up": TagAssignment(groups: ["Chest"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Decline Push-Up": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Pike Push-Up": TagAssignment(groups: ["Shoulders"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Handstand Push-Up": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Bodyweight"], workouts: ["Push", "Upper Body"]),
            "Knee Push-Up": TagAssignment(groups: ["Chest"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Archer Push-Up": TagAssignment(groups: ["Chest", "Arms"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Clap Push-Up": TagAssignment(groups: ["Chest", "Arms"], categories: ["Bodyweight"], workouts: ["HIIT", "Push"]),
            "Hindu Push-Up": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Bodyweight"], workouts: ["Full Body"]),

            // MARK: - Squats
            "Squat": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Narrow Squat": TagAssignment(groups: ["Quads"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Wide Squat": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Sumo Squat": TagAssignment(groups: ["Glutes", "Inner Thighs"].filter { $0 != "Inner Thighs" }, categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Pulse Squat": TagAssignment(groups: ["Quads"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Jump Squat": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["HIIT", "Cardio"]),
            "Box Squat": TagAssignment(groups: ["Glutes", "Quads"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Wall Sit": TagAssignment(groups: ["Quads"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Single-Leg Squat": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Pistol Squat": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),

            // MARK: - Lunges
            "Reverse Lunge": TagAssignment(groups: ["Glutes", "Quads"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Forward Lunge": TagAssignment(groups: ["Quads"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Walking Lunge": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["Lower Body", "Cardio"]),
            "Curtsy Lunge": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Jumping Lunge": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["HIIT", "Cardio"]),
            "Side Lunge": TagAssignment(groups: ["Glutes", "Quads"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Step-Back Lunge": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),

            // MARK: - Glutes & Calves
            "Glute Bridge": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Single-Leg Glute Bridge": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Hip Thrust (Bodyweight)": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Donkey Kicks": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Fire Hydrants": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Calf Raise": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["Lower Body"]),
            "Single-Leg Calf Raise": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["Lower Body"]),

            // MARK: - Conditioning / Locomotion
            "Burpees": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["HIIT", "Cardio"]),
            "Half Burpee": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Bear Crawl": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Full Body"]),
            "Crab Walk": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Full Body"]),
            "Inchworm": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Jumping Jacks": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Cardio"]),
            "Star Jumps": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Cardio"]),
            "High Knees": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["Cardio"]),
            "Butt Kicks": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["Cardio"]),
            "Skater Jumps": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Tuck Jumps": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Broad Jumps": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Standing Long Jump": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["HIIT"]),

            // MARK: - Core
            "Sit-Up": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),
            "Toe Touches": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),
            "Scissor Kicks": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),
            "Leg Raises": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),
            "Hollow Hold": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Back Extension (Floor)": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Bird Dog": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Standing Oblique Crunch": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),
            "Russian Twist (Bodyweight)": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),
            "Seated Knee Tucks": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),
            "L-Sit": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Upper Body"]),

            // MARK: - Hanging Core
            "Hanging Knee Raise": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),
            "Hanging Leg Raise": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Core"]),

            // MARK: - Pull
            "Pull-Up": TagAssignment(groups: ["Back", "Arms"], categories: ["Bodyweight"], workouts: ["Pull", "Upper Body"]),
            "Chin-Up": TagAssignment(groups: ["Back", "Biceps"], categories: ["Bodyweight"], workouts: ["Pull"]),
            "Neutral Grip Pull-Up": TagAssignment(groups: ["Back", "Arms"], categories: ["Bodyweight"], workouts: ["Pull"]),
            "Wide Grip Pull-Up": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Pull"]),
            "Australian Pull-Up": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Pull"]),
            "Negative Pull-Up": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Pull"]),
            "Isometric Pull-Up Hold": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Pull"]),

            // MARK: - Dips
            "Dip (Bodyweight)": TagAssignment(groups: ["Triceps", "Chest"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Bench Dip": TagAssignment(groups: ["Triceps"], categories: ["Bodyweight"], workouts: ["Push"]),
            "Straight Arm Dip": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Bodyweight"], workouts: ["Push"]),
            
            "Dumbbell Bench Press": TagAssignment(groups: ["Chest"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Incline Bench Press": TagAssignment(groups: ["Chest"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Decline Bench Press": TagAssignment(groups: ["Chest"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Chest Fly": TagAssignment(groups: ["Chest"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Incline Dumbbell Fly": TagAssignment(groups: ["Chest"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Pullover": TagAssignment(groups: ["Chest", "Back"], categories: ["Dumbbell"], workouts: ["Push", "Pull"]),
            "Dumbbell Shoulder Press": TagAssignment(groups: ["Shoulders"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Seated Dumbbell Shoulder Press": TagAssignment(groups: ["Shoulders"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Arnold Press": TagAssignment(groups: ["Shoulders"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Front Raise": TagAssignment(groups: ["Shoulders"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Lateral Raise": TagAssignment(groups: ["Shoulders"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Upright Row": TagAssignment(groups: ["Shoulders", "Back"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Dumbbell Shrugs": TagAssignment(groups: ["Shoulders", "Back"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Dumbbell Bent-Over Row": TagAssignment(groups: ["Back"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Single-Arm Dumbbell Row": TagAssignment(groups: ["Back"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Dumbbell Renegade Row": TagAssignment(groups: ["Back", "Core"], categories: ["Dumbbell"], workouts: ["Pull", "Full Body"]),
            "Dumbbell Deadlift": TagAssignment(groups: ["Back", "Hamstrings"], categories: ["Dumbbell"], workouts: ["Pull", "Full Body"]),
            "Dumbbell Romanian Deadlift": TagAssignment(groups: ["Hamstrings", "Glutes"], categories: ["Dumbbell"], workouts: ["Pull", "Lower Body"]),
            "Dumbbell Sumo Deadlift": TagAssignment(groups: ["Glutes", "Hamstrings"], categories: ["Dumbbell"], workouts: ["Pull", "Lower Body"]),
            "Dumbbell Squat": TagAssignment(groups: ["Quads", "Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Goblet Squat": TagAssignment(groups: ["Quads", "Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Front Squat": TagAssignment(groups: ["Quads"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Split Squat": TagAssignment(groups: ["Quads", "Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Bulgarian Split Squat": TagAssignment(groups: ["Quads", "Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Reverse Lunge": TagAssignment(groups: ["Quads", "Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Walking Lunge": TagAssignment(groups: ["Quads", "Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Step-Up": TagAssignment(groups: ["Quads", "Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Hip Thrust": TagAssignment(groups: ["Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Glute Bridge": TagAssignment(groups: ["Glutes"], categories: ["Dumbbell"], workouts: ["Leg", "Lower Body"]),
            "Dumbbell Calf Raise": TagAssignment(groups: ["Legs"], categories: ["Dumbbell"], workouts: ["Leg"]),
            "Seated Dumbbell Calf Raise": TagAssignment(groups: ["Legs"], categories: ["Dumbbell"], workouts: ["Leg"]),
            "Dumbbell Bicep Curl": TagAssignment(groups: ["Biceps"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Alternating Dumbbell Curl": TagAssignment(groups: ["Biceps"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Hammer Curl": TagAssignment(groups: ["Biceps"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Cross-Body Hammer Curl": TagAssignment(groups: ["Biceps"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Concentration Curl": TagAssignment(groups: ["Biceps"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Incline Dumbbell Curl": TagAssignment(groups: ["Biceps"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Zottman Curl": TagAssignment(groups: ["Biceps"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Dumbbell Tricep Extension": TagAssignment(groups: ["Triceps"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Overhead Dumbbell Tricep Extension": TagAssignment(groups: ["Triceps"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Single-Arm Dumbbell Tricep Extension": TagAssignment(groups: ["Triceps"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Skull Crushers": TagAssignment(groups: ["Triceps"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Kickbacks": TagAssignment(groups: ["Triceps"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Close-Grip Dumbbell Press": TagAssignment(groups: ["Chest", "Triceps"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Wrist Curl": TagAssignment(groups: ["Arms"], categories: ["Dumbbell"], workouts: ["Upper Body"]),
            "Reverse Dumbbell Wrist Curl": TagAssignment(groups: ["Arms"], categories: ["Dumbbell"], workouts: ["Upper Body"]),
            "Dumbbell Farmer's Carry": TagAssignment(groups: ["Arms", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Single-Arm Dumbbell Carry": TagAssignment(groups: ["Arms", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Dumbbell Suitcase Carry": TagAssignment(groups: ["Arms", "Core"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Dumbbell Russian Twist": TagAssignment(groups: ["Core"], categories: ["Dumbbell"], workouts: ["Full Body", "Core"]),
            "Dumbbell Side Bend": TagAssignment(groups: ["Obliques"], categories: ["Dumbbell"], workouts: ["Core"]),
            "Dumbbell Woodchopper": TagAssignment(groups: ["Core"], categories: ["Dumbbell"], workouts: ["Full Body", "Core"]),
            "Dumbbell Sit-Up": TagAssignment(groups: ["Core"], categories: ["Dumbbell"], workouts: ["Core"]),
            "Dumbbell V-Up": TagAssignment(groups: ["Core"], categories: ["Dumbbell"], workouts: ["Core"]),
            "Dumbbell Thruster": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Push"]),
            "Dumbbell Clean": TagAssignment(groups: ["Full Body", "Back"], categories: ["Dumbbell"], workouts: ["Full Body", "Pull"]),
            "Dumbbell Clean and Press": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Push"]),
            "Dumbbell Snatch": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Pull"]),
            "Single-Arm Dumbbell Snatch": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Pull"]),
            "Dumbbell Push Press": TagAssignment(groups: ["Shoulders"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell High Pull": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Dumbbell Turkish Get-Up": TagAssignment(groups: ["Full Body", "Core"], categories: ["Dumbbell"], workouts: ["Full Body", "Recovery"]),
            "Dumbbell Windmill": TagAssignment(groups: ["Shoulders", "Core"], categories: ["Dumbbell"], workouts: ["Full Body", "Core"]),
            "Dumbbell Reverse Fly": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Incline Dumbbell Reverse Fly": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Dumbbell"], workouts: ["Pull", "Upper Body"]),
            "Dumbbell Cuban Press": TagAssignment(groups: ["Shoulders"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Around the World": TagAssignment(groups: ["Shoulders", "Chest"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Floor Press": TagAssignment(groups: ["Chest"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Single-Arm Dumbbell Floor Press": TagAssignment(groups: ["Chest"], categories: ["Dumbbell"], workouts: ["Push", "Upper Body"]),
            "Dumbbell Pull-Over Crunch": TagAssignment(groups: ["Chest", "Core"], categories: ["Dumbbell"], workouts: ["Core", "Upper Body"]),

            "Barbell Back Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Front Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Box Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Pause Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Overhead Squat": TagAssignment(groups: ["Legs", "Shoulders"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Zercher Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Split Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Lunge": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Walking Lunge": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Reverse Lunge": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Deadlift": TagAssignment(groups: ["Back", "Hamstrings"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Conventional Deadlift": TagAssignment(groups: ["Back", "Hamstrings"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Sumo Deadlift": TagAssignment(groups: ["Back", "Quads"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Romanian Deadlift": TagAssignment(groups: ["Hamstrings", "Glutes"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Stiff-Leg Deadlift": TagAssignment(groups: ["Hamstrings", "Glutes"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Deficit Deadlift": TagAssignment(groups: ["Back", "Hamstrings"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Rack Pull": TagAssignment(groups: ["Back", "Hamstrings"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Hip Thrust": TagAssignment(groups: ["Glutes", "Hamstrings"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Glute Bridge": TagAssignment(groups: ["Glutes", "Hamstrings"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Barbell Bench Press": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Incline Bench Press": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Decline Bench Press": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Close-Grip Bench Press": TagAssignment(groups: ["Chest", "Triceps"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Paused Bench Press": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Spoto Press": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Floor Press": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Overhead Press": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Standing Military Press": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Seated Barbell Shoulder Press": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Push Press": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Split Jerk": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Push Jerk": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Upright Row": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell High Pull": TagAssignment(groups: ["Shoulders", "Back"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Bent-Over Row": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Pendlay Row": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Yates Row": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Meadows Row": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Shrug": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Curl": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "EZ-Bar Curl": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Wide-Grip Barbell Curl": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Reverse Barbell Curl": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Drag Curl": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Preacher Curl": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Skull Crushers": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "EZ-Bar Skull Crushers": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Close-Grip Barbell Press": TagAssignment(groups: ["Chest", "Triceps"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "JM Press": TagAssignment(groups: ["Chest", "Triceps"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Tricep Extension": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Wrist Curl": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Reverse Barbell Wrist Curl": TagAssignment(groups: ["Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Barbell Farmer’s Walk": TagAssignment(groups: ["Full Body", "Back"], categories: ["Barbell"], workouts: ["Full Body", "Cardio"]),
            "Barbell Rollout": TagAssignment(groups: ["Core"], categories: ["Barbell"], workouts: ["Full Body", "Recovery"]),
            "Standing Barbell Ab Rollout": TagAssignment(groups: ["Core"], categories: ["Barbell"], workouts: ["Full Body", "Recovery"]),
            "Landmine Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Barbell"], workouts: ["Lower Body", "Full Body"]),
            "Landmine Press": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Landmine Row": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Barbell"], workouts: ["Upper Body", "Full Body"]),
            "Landmine Rotation": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Barbell Clean": TagAssignment(groups: ["Legs", "Back"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Power Clean": TagAssignment(groups: ["Legs", "Back"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Hang Clean": TagAssignment(groups: ["Legs", "Back"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Clean and Jerk": TagAssignment(groups: ["Legs", "Shoulders"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Barbell Snatch": TagAssignment(groups: ["Legs", "Shoulders"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Power Snatch": TagAssignment(groups: ["Legs", "Shoulders"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Hang Snatch": TagAssignment(groups: ["Legs", "Shoulders"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Muscle Snatch": TagAssignment(groups: ["Legs", "Shoulders"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Barbell Thruster": TagAssignment(groups: ["Legs", "Shoulders"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            "Barbell Windmill": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Barbell"], workouts: ["Full Body", "Recovery"]),
            "Barbell Side Bend": TagAssignment(groups: ["Core", "Obliques"], categories: ["Barbell"], workouts: ["Full Body", "Upper Body"]),
            
            "Leg Press Machine": TagAssignment(groups: ["Legs", "Quads"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Hack Squat Machine": TagAssignment(groups: ["Legs", "Quads"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Smith Machine Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Smith Machine Front Squat": TagAssignment(groups: ["Legs", "Quads"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Smith Machine Lunge": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Smith Machine Romanian Deadlift": TagAssignment(groups: ["Legs", "Hamstrings"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Seated Leg Curl Machine": TagAssignment(groups: ["Legs", "Hamstrings"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Lying Leg Curl Machine": TagAssignment(groups: ["Legs", "Hamstrings"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Standing Leg Curl Machine": TagAssignment(groups: ["Legs", "Hamstrings"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Leg Extension Machine": TagAssignment(groups: ["Legs", "Quads"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Hip Abductor Machine": TagAssignment(groups: ["Glutes"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Hip Adductor Machine": TagAssignment(groups: ["Glutes"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Standing Calf Raise Machine": TagAssignment(groups: ["Legs", "Calves"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Seated Calf Raise Machine": TagAssignment(groups: ["Legs", "Calves"], categories: ["Machine"], workouts: ["Leg", "Full Body"]),
            "Chest Press Machine": TagAssignment(groups: ["Chest"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Incline Chest Press Machine": TagAssignment(groups: ["Chest"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Pec Deck Machine": TagAssignment(groups: ["Chest"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Rear Delt Fly Machine": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Seated Row Machine": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Iso-Lateral Row Machine": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Lat Pulldown": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Wide-Grip Lat Pulldown": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Close-Grip Lat Pulldown": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Reverse-Grip Lat Pulldown": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Assisted Pull-Up Machine": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Chest Fly": TagAssignment(groups: ["Chest"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Low Cable Chest Fly": TagAssignment(groups: ["Chest"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "High Cable Chest Fly": TagAssignment(groups: ["Chest"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Crossover": TagAssignment(groups: ["Chest"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Shoulder Press": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Front Raise": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Lateral Raise": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Upright Row": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Face Pull": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Rear Delt Fly": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Straight-Arm Pulldown": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Row": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Single-Arm Cable Row": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable High Row": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Shrugs": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Bicep Curl": TagAssignment(groups: ["Arms", "Biceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Single-Arm Cable Curl": TagAssignment(groups: ["Arms", "Biceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Hammer Curl": TagAssignment(groups: ["Arms", "Biceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Preacher Curl": TagAssignment(groups: ["Arms", "Biceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Tricep Pushdown": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Rope Tricep Pushdown": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "V-Bar Tricep Pushdown": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Overhead Tricep Extension": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Single-Arm Cable Tricep Extension": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Kickback": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Cable Pallof Press": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Recovery"]),
            "Machine Ab Crunch": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Recovery"]),
            "Captain’s Chair Knee Raise": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Recovery"]),
            "Captain’s Chair Leg Raise": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Recovery"]),
            "Back Extension Machine": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Full Body", "Recovery"]),
            "Reverse Hyper Machine": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Full Body", "Recovery"]),
            "Glute Kickback Machine": TagAssignment(groups: ["Glutes"], categories: ["Machine"], workouts: ["Full Body", "Leg"]),
            "Hip Thrust Machine": TagAssignment(groups: ["Glutes"], categories: ["Machine"], workouts: ["Full Body", "Leg"]),
            "Assisted Dip Machine": TagAssignment(groups: ["Arms", "Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Machine Shoulder Press": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Machine Lateral Raise": TagAssignment(groups: ["Shoulders"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Machine Bicep Curl": TagAssignment(groups: ["Arms", "Biceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            "Machine Tricep Extension": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Machine"], workouts: ["Upper Body", "Full Body"]),
            
            "Kettlebell Deadlift": TagAssignment(groups: ["Back", "Legs"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Kettlebell Sumo Deadlift": TagAssignment(groups: ["Legs", "Back"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Single-Arm Kettlebell Deadlift": TagAssignment(groups: ["Legs", "Back"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Kettlebell Swing": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body", "Cardio"]),
            "American Kettlebell Swing": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body", "Cardio"]),
            "Single-Arm Kettlebell Swing": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Goblet Squat": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Kettlebell Front Squat": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Double Kettlebell Squat": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Kettlebell Lunge": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Kettlebell Reverse Lunge": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Kettlebell Walking Lunge": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Kettlebell Step-Up": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Kettlebell", "Bodyweight"], workouts: ["Full Body"]),
            "Kettlebell Clean": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Single-Arm Kettlebell Clean": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Clean and Press": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Press": TagAssignment(groups: ["Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Single-Arm Kettlebell Press": TagAssignment(groups: ["Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Push Press": TagAssignment(groups: ["Shoulders", "Full Body"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Jerk": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Snatch": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Single-Arm Kettlebell Snatch": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell High Pull": TagAssignment(groups: ["Full Body", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Upright Row": TagAssignment(groups: ["Shoulders", "Back"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Bent-Over Row": TagAssignment(groups: ["Back"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Single-Arm Kettlebell Row": TagAssignment(groups: ["Back"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Floor Press": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Single-Arm Kettlebell Floor Press": TagAssignment(groups: ["Chest", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Chest Press": TagAssignment(groups: ["Chest"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Fly": TagAssignment(groups: ["Chest"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Halo": TagAssignment(groups: ["Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Around the Body": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Windmill": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Turkish Get-Up": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Half Turkish Get-Up": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Side Bend": TagAssignment(groups: ["Core"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Russian Twist": TagAssignment(groups: ["Core"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Sit-Up": TagAssignment(groups: ["Core"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell V-Up": TagAssignment(groups: ["Core"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Dead Bug": TagAssignment(groups: ["Core"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Plank Drag": TagAssignment(groups: ["Core"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Renegade Row": TagAssignment(groups: ["Back", "Core"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Farmer’s Carry": TagAssignment(groups: ["Full Body"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Single-Arm Kettlebell Carry": TagAssignment(groups: ["Full Body"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Suitcase Carry": TagAssignment(groups: ["Full Body"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Overhead Carry": TagAssignment(groups: ["Full Body"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Double Kettlebell Front Rack Carry": TagAssignment(groups: ["Full Body"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell March": TagAssignment(groups: ["Full Body"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Reverse Fly": TagAssignment(groups: ["Shoulders", "Back"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Curl": TagAssignment(groups: ["Arms", "Biceps"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Hammer Curl": TagAssignment(groups: ["Arms", "Biceps"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Tricep Extension": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Skull Crushers": TagAssignment(groups: ["Arms", "Triceps"], categories: ["Kettlebell"], workouts: ["Full Body"]),
            "Kettlebell Thruster": TagAssignment(groups: ["Shoulders", "Legs"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Squat Clean": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Clean Squat Press": TagAssignment(groups: ["Shoulders", "Legs"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Lateral Lunge": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Cossack Squat": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Deadlift to High Pull": TagAssignment(groups: ["Back", "Glutes"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Figure 8": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Figure 8 to Hold": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Bottoms-Up Press": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Bottoms-Up Carry": TagAssignment(groups: ["Shoulders", "Arms"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Squat Press": TagAssignment(groups: ["Legs", "Shoulders"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Single-Leg Deadlift": TagAssignment(groups: ["Glutes", "Hamstrings"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Pistol Squat": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),
            "Kettlebell Jump Squat": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Dumbbell"], workouts: ["Full Body", "Cardio"]),

            "Running": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Jogging": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Sprinting": TagAssignment(groups: ["Legs"], categories: ["Duration"], workouts: ["Cardio", "HIIT"]),
            "Treadmill Running": TagAssignment(groups: ["Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Incline Treadmill Walking": TagAssignment(groups: ["Cardio", "Legs"], categories: ["Machine"], workouts: ["Cardio"]),
            "Walking (Outdoor)": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Walking (Indoor)": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Walking (Treadmill)": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Power Walking": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Hiking": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Stair Climbing": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Stairmaster": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Elliptical Trainer": TagAssignment(groups: ["Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Rowing Machine": TagAssignment(groups: ["Back", "Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Air Bike": TagAssignment(groups: ["Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Stationary Bike": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Spin Bike": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Assault Bike": TagAssignment(groups: ["Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Ski Erg": TagAssignment(groups: ["Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Jump Rope": TagAssignment(groups: ["Cardio"], categories: ["Bodyweight"], workouts: ["Cardio", "HIIT"]),
            "Double Unders": TagAssignment(groups: ["Cardio"], categories: ["Bodyweight"], workouts: ["Cardio", "HIIT"]),
            "Jump Rope High Knees": TagAssignment(groups: ["Cardio"], categories: ["Bodyweight"], workouts: ["Cardio", "HIIT"]),
            "Box Jumps": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Depth Jumps": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Plyometric Lunges": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Plyometric Push-Ups": TagAssignment(groups: ["Arms", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Medicine Ball Slams": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Wall Balls": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Medicine Ball Chest Pass": TagAssignment(groups: ["Arms", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Medicine Ball Rotational Throw": TagAssignment(groups: ["Core", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Battle Ropes": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Alternating Battle Ropes": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Battle Rope Slams": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Sled Push": TagAssignment(groups: ["Legs", "Full Body"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Sled Pull": TagAssignment(groups: ["Legs", "Full Body"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Farmer’s Walk": TagAssignment(groups: ["Full Body", "Legs"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Yoke Carry": TagAssignment(groups: ["Full Body", "Legs"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Tire Flips": TagAssignment(groups: ["Full Body", "Legs"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Bear Crawl Sprint": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Shuttle Runs": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Agility Ladder Drills": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Cone Drills": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Suicides": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Fartlek Training": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Tempo Runs": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Interval Running": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Hill Sprints": TagAssignment(groups: ["Cardio", "Legs"], categories: ["Duration"], workouts: ["Cardio"]),
            "Swimming": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Freestyle Swimming": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Backstroke Swimming": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Breaststroke Swimming": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Butterfly Swimming": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Pool Walking": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Aqua Jogging": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Cycling": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Road Cycling": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Mountain Biking": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Indoor Cycling": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Machine"], workouts: ["Cardio"]),
            "Rollerblading": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Rowing (On Water)": TagAssignment(groups: ["Back", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Snowshoeing": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Duration"], workouts: ["Cardio"]),
            "Jumping Lunges": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Shadow Boxing": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["Cardio"]),
            "Heavy Bag Boxing": TagAssignment(groups: ["Full Body", "Arms"], categories: ["Bodyweight"], workouts: ["Cardio"]),
            "HIIT Workout": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["HIIT"]),
            "Tabata Workout": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["HIIT", "Cardio"]),
            "AMRAP Workout": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["Full Body", "HIIT"]),
            "EMOM Workout": TagAssignment(groups: ["Cardio"], categories: ["Duration"], workouts: ["Full Body", "HIIT"]),
            "Strongman Conditioning": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight", "Dumbbell"], workouts: ["Full Body", "Sport"]),
           
            "Plank Hold": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Side Plank Hold": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Plank with Shoulder Taps": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Plank with Leg Lift": TagAssignment(groups: ["Core", "Glutes"], categories: ["Bodyweight"], workouts: ["Full Body", "Lower Body"]),
            "Plank to Push-Up": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Upper Body", "Full Body"]),
            "Reverse Plank": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Hollow Body Hold": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Arch Hold": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Dead Bug": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Crunch": TagAssignment(groups: ["Abs", "Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Reverse Crunch": TagAssignment(groups: ["Abs", "Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Lower Body"]),
            "Bicycle Crunch": TagAssignment(groups: ["Abs", "Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Toe Touch Crunch": TagAssignment(groups: ["Abs", "Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Heel Taps": TagAssignment(groups: ["Abs", "Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Butterfly Sit-Up": TagAssignment(groups: ["Abs", "Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "V-Up": TagAssignment(groups: ["Abs", "Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Jackknife Sit-Up": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Seated Leg Raises": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Lower Body"]),
            "Lying Leg Raises": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Lower Body"]),
            "Hanging Knee Raises": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Hanging Leg Raises": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Hanging Windshield Wipers": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Flutter Kicks": TagAssignment(groups: ["Abs"], categories: ["Bodyweight"], workouts: ["Full Body", "Lower Body"]),
            "Russian Twist": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Weighted Russian Twist": TagAssignment(groups: ["Core"], categories: ["Dumbbell"], workouts: ["Full Body", "Upper Body"]),
            "Oblique Crunch": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Side Bend": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Cable Crunch": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Cable Oblique Crunch": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Cable Woodchopper": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Low to High Woodchopper": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "High to Low Woodchopper": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Pallof Press": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Anti-Rotation Hold": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Ab Wheel Rollout": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Kneeling Ab Rollout": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Standing Ab Rollout": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "TRX Plank": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "TRX Pike": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "TRX Knee Tucks": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "TRX Body Saw": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Medicine Ball Sit-Up": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Medicine Ball V-Up": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Medicine Ball Russian Twist": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Stability Ball Crunch": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Stability Ball Pike": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Stability Ball Rollout": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Stability Ball Pass": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Swiss Ball Knee Tuck": TagAssignment(groups: ["Core"], categories: ["Machine"], workouts: ["Full Body", "Upper Body"]),
            "Back Extension": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Full Body", "Lower Body"]),
            "Roman Chair Back Extension": TagAssignment(groups: ["Back"], categories: ["Machine"], workouts: ["Full Body", "Lower Body"]),
            "Superman Hold": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Good Morning (Bodyweight)": TagAssignment(groups: ["Back", "Glutes"], categories: ["Bodyweight"], workouts: ["Full Body", "Lower Body"]),
            "Reverse Hyperextension": TagAssignment(groups: ["Back", "Glutes"], categories: ["Machine"], workouts: ["Full Body", "Lower Body"]),
            "Jefferson Curl": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Full Body", "Lower Body"]),
            "Farmer’s Carry Core Hold": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Suitcase Carry Core Hold": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Overhead Carry Core Hold": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Turkish Get-Up (Core Focus)": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Full Body", "Upper Body"]),
            "Bear Crawl Hold": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Mountain Climbers": TagAssignment(groups: ["Core", "Cardio"], categories: ["Bodyweight", "Cardio"], workouts: ["Full Body", "HIIT"]),
            "Cross-Body Mountain Climbers": TagAssignment(groups: ["Core", "Cardio"], categories: ["Bodyweight", "Cardio"], workouts: ["Full Body", "HIIT"]),
            "Side Plank Hip Dips": TagAssignment(groups: ["Core", "Obliques"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),
            "Copenhagen Plank": TagAssignment(groups: ["Core", "Adductors"], categories: ["Bodyweight"], workouts: ["Full Body", "Recovery"]),

            "Neck Flexion Stretch": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Neck Extension Stretch": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Neck Side Bend Stretch": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Neck Rotation Stretch": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Upper Trapezius Stretch": TagAssignment(groups: ["Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Levator Scapulae Stretch": TagAssignment(groups: ["Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Shoulder Rolls": TagAssignment(groups: ["Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Arm Circles": TagAssignment(groups: ["Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Cross-Body Shoulder Stretch": TagAssignment(groups: ["Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Overhead Triceps Stretch": TagAssignment(groups: ["Arms", "Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Chest Opener Stretch": TagAssignment(groups: ["Chest"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Doorway Chest Stretch": TagAssignment(groups: ["Chest"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Shoulder Dislocates (Band)": TagAssignment(groups: ["Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Scapular Push-Ups": TagAssignment(groups: ["Shoulders", "Chest"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Scapular Pull-Ups": TagAssignment(groups: ["Shoulders", "Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Cat Cow Stretch": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Thoracic Spine Rotation": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Thoracic Extension on Foam Roller": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Child’s Pose": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Thread the Needle Stretch": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Cobra Stretch": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Upward Dog": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Downward Dog": TagAssignment(groups: ["Back", "Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "World’s Greatest Stretch": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Standing Forward Fold": TagAssignment(groups: ["Hamstrings"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Seated Forward Fold": TagAssignment(groups: ["Hamstrings"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Jefferson Curl (Mobility)": TagAssignment(groups: ["Back", "Hamstrings"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Hip Flexor Stretch": TagAssignment(groups: ["Hip Flexors"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Half-Kneeling Hip Flexor Stretch": TagAssignment(groups: ["Hip Flexors"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Couch Stretch": TagAssignment(groups: ["Hip Flexors", "Quads"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Figure Four Stretch": TagAssignment(groups: ["Glutes", "Hip Flexors"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Piriformis Stretch": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Glute Stretch": TagAssignment(groups: ["Glutes"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Seated Spinal Twist": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Supine Spinal Twist": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "90/90 Hip Stretch": TagAssignment(groups: ["Hip Flexors", "Glutes"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Hip CARs": TagAssignment(groups: ["Hip Flexors"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Ankle CARs": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Shoulder CARs": TagAssignment(groups: ["Shoulders"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Wrist CARs": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Deep Squat Hold": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Goblet Squat Hold": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Adductor Rockbacks": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Hamstring Stretch (Standing)": TagAssignment(groups: ["Hamstrings"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Hamstring Stretch (Seated)": TagAssignment(groups: ["Hamstrings"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Hamstring Stretch (Lying)": TagAssignment(groups: ["Hamstrings"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Calf Stretch (Wall)": TagAssignment(groups: ["Calves"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Soleus Stretch": TagAssignment(groups: ["Calves"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Quad Stretch (Standing)": TagAssignment(groups: ["Quads"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Quad Stretch (Side-Lying)": TagAssignment(groups: ["Quads"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Frog Stretch": TagAssignment(groups: ["Groin"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Butterfly Stretch": TagAssignment(groups: ["Groin"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Happy Baby Pose": TagAssignment(groups: ["Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Pigeon Pose": TagAssignment(groups: ["Glutes", "Hip Flexors"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Lizard Pose": TagAssignment(groups: ["Hip Flexors", "Glutes"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Low Lunge Stretch": TagAssignment(groups: ["Hip Flexors", "Quads"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Standing Side Bend Stretch": TagAssignment(groups: ["Core", "Other"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Lat Stretch (Overhead)": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Lat Stretch (Bench)": TagAssignment(groups: ["Back"], categories: ["Bodyweight"], workouts: ["Recovery"]),
            "Foam Rolling Quads": TagAssignment(groups: ["Legs", "Quads"], categories: ["Other"], workouts: ["Recovery"]),
            "Foam Rolling Hamstrings": TagAssignment(groups: ["Legs", "Hamstrings"], categories: ["Other"], workouts: ["Recovery"]),
            "Foam Rolling Glutes": TagAssignment(groups: ["Legs", "Glutes"], categories: ["Other"], workouts: ["Recovery"]),
            "Foam Rolling IT Band": TagAssignment(groups: ["Legs"], categories: ["Other"], workouts: ["Recovery"]),
            "Foam Rolling Calves": TagAssignment(groups: ["Legs", "Calves"], categories: ["Other"], workouts: ["Recovery"]),
            "Foam Rolling Upper Back": TagAssignment(groups: ["Back"], categories: ["Other"], workouts: ["Recovery"]),
            "Foam Rolling Lats": TagAssignment(groups: ["Back"], categories: ["Other"], workouts: ["Recovery"]),
            "Foam Rolling Chest": TagAssignment(groups: ["Chest"], categories: ["Other"], workouts: ["Recovery"]),
            "Foam Rolling Shoulders": TagAssignment(groups: ["Shoulders"], categories: ["Other"], workouts: ["Recovery"]),
            "Breathing Drill (Diaphragmatic)": TagAssignment(groups: ["Other"], categories: ["Other"], workouts: ["Recovery"]),
            "Box Breathing": TagAssignment(groups: ["Other"], categories: ["Other"], workouts: ["Recovery"]),
            "Crocodile Breathing": TagAssignment(groups: ["Other"], categories: ["Other"], workouts: ["Recovery"]),
            "Parasympathetic Breathing": TagAssignment(groups: ["Other"], categories: ["Other"], workouts: ["Recovery"]),
            "Guided Stretching Session": TagAssignment(groups: ["Other"], categories: ["Other"], workouts: ["Recovery"]),
            "Active Recovery Walk": TagAssignment(groups: ["Other"], categories: ["Cardio"], workouts: ["Recovery"]),
            "Yoga Flow": TagAssignment(groups: ["Core", "Full Body"], categories: ["Bodyweight"], workouts: ["Full Body", "Yoga"]),
            "Restorative Yoga": TagAssignment(groups: ["Core", "Full Body"], categories: ["Bodyweight"], workouts: ["Full Body", "Yoga"]),
            "Mobility Flow": TagAssignment(groups: ["Core", "Full Body"], categories: ["Bodyweight"], workouts: ["Full Body", "Yoga"]),
            
            "Soccer": TagAssignment(groups: ["Cardio", "Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Futsal": TagAssignment(groups: ["Cardio", "Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Beach Soccer": TagAssignment(groups: ["Cardio", "Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "American Football": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Flag Football": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Arena Football": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Basketball": TagAssignment(groups: ["Cardio", "Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Baseball": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Softball": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Fastpitch Softball": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Cricket": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Test Cricket": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "One Day Cricket": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "T20 Cricket": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Rugby Union": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Rugby League": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Rugby Sevens": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Ice Hockey": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Field Hockey": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Roller Hockey": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Lacrosse": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Box Lacrosse": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Tennis": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Doubles Tennis": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Table Tennis": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Badminton": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Squash": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Racquetball": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Padel": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Pickleball": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Volleyball (Indoor)": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Volleyball (Sand)": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Volleyball (Grass)": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Beach Handball": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Handball (Indoor)": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Water Polo": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Open Water Swimming": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Diving": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Surfing": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Bodyboarding": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Stand-Up Paddleboarding": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Rowing": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Kayaking": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Canoeing": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Sailing": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Cycling (Road)": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Cycling (Track)": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Cycling (Mountain)": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "BMX Racing": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "BMX Freestyle": TagAssignment(groups: ["Legs", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Triathlon": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Duathlon": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Athletics (Track & Field)": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Cross Country Running": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Marathon Running": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Trail Running": TagAssignment(groups: ["Full Body", "Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Wrestling (Freestyle)": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Wrestling (Greco-Roman)": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Judo": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Brazilian Jiu-Jitsu": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Karate": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Taekwondo": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Boxing": TagAssignment(groups: ["Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Kickboxing": TagAssignment(groups: ["Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Muay Thai": TagAssignment(groups: ["Cardio"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Mixed Martial Arts": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Golf": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Disc Golf": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Bowling": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Skateboarding": TagAssignment(groups: ["Full Body"], categories: ["Bodyweight"], workouts: ["Sport"]),
            "Snowboarding": TagAssignment(groups: ["Full Body", "Legs"], categories: ["Bodyweight"], workouts: ["Sport", "Cardio"]),
            "Alpine Skiing": TagAssignment(groups: ["Full Body", "Legs"], categories: ["Bodyweight"], workouts: ["Sport", "Cardio"]),
            "Cross-Country Skiing": TagAssignment(groups: ["Full Body", "Legs"], categories: ["Bodyweight"], workouts: ["Sport", "Cardio"]),
            "Figure Skating": TagAssignment(groups: ["Full Body", "Legs"], categories: ["Bodyweight"], workouts: ["Sport", "Cardio"]),
            "Speed Skating": TagAssignment(groups: ["Full Body", "Legs"], categories: ["Bodyweight"], workouts: ["Sport", "Cardio"]),
            "Curling": TagAssignment(groups: ["Full Body", "Arms"], categories: ["Bodyweight"], workouts: ["Sport"]),
            
            "Mountain Pose (Tadasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Downward-Facing Dog (Adho Mukha Svanasana)": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Upward-Facing Dog (Urdhva Mukha Svanasana)": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Plank Pose (Phalakasana)": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Chaturanga Dandasana": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Child’s Pose (Balasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Cobra Pose (Bhujangasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Warrior I (Virabhadrasana I)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Warrior II (Virabhadrasana II)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Warrior III (Virabhadrasana III)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Triangle Pose (Trikonasana)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Extended Side Angle Pose (Utthita Parsvakonasana)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Tree Pose (Vrksasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Chair Pose (Utkatasana)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Bridge Pose (Setu Bandha Sarvangasana)": TagAssignment(groups: ["Glutes", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Wheel Pose (Urdhva Dhanurasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Seated Forward Fold (Paschimottanasana)": TagAssignment(groups: ["Core", "Hamstrings"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Standing Forward Fold (Uttanasana)": TagAssignment(groups: ["Core", "Hamstrings"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Half Forward Fold (Ardha Uttanasana)": TagAssignment(groups: ["Core", "Hamstrings"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Easy Pose (Sukhasana)": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Lotus Pose (Padmasana)": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Half Lotus Pose (Ardha Padmasana)": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Bound Angle Pose (Baddha Konasana)": TagAssignment(groups: ["Core", "Hip Flexors"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Crescent Lunge (Anjaneyasana)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Low Lunge (Ashwa Sanchalanasana)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Pyramid Pose (Parsvottanasana)": TagAssignment(groups: ["Core", "Hamstrings"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Garland Pose (Malasana)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Boat Pose (Navasana)": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Cat Pose (Marjaryasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Cow Pose (Bitilasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Camel Pose (Ustrasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Bow Pose (Dhanurasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Fish Pose (Matsyasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Corpse Pose (Savasana)": TagAssignment(groups: ["Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Happy Baby Pose (Ananda Balasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Supine Twist (Supta Matsyendrasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Reclining Hand-to-Big-Toe Pose (Supta Padangusthasana)": TagAssignment(groups: ["Core", "Hamstrings"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Eagle Pose (Garudasana)": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Half Moon Pose (Ardha Chandrasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Side Plank Pose (Vasisthasana)": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Dolphin Pose (Ardha Pincha Mayurasana)": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Crow Pose (Bakasana)": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Pigeon Pose (Eka Pada Rajakapotasana)": TagAssignment(groups: ["Core", "Hip Flexors"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Lizard Pose (Utthan Pristhasana)": TagAssignment(groups: ["Core", "Hip Flexors"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Seated Twist (Ardha Matsyendrasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Wide-Legged Forward Fold (Prasarita Padottanasana)": TagAssignment(groups: ["Core", "Hamstrings"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Reverse Warrior (Viparita Virabhadrasana)": TagAssignment(groups: ["Legs", "Core"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Extended Hand-to-Big-Toe Pose (Utthita Hasta Padangusthasana)": TagAssignment(groups: ["Core", "Hamstrings"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Fire Log Pose (Agnistambhasana)": TagAssignment(groups: ["Core", "Hip Flexors"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Thread the Needle Pose": TagAssignment(groups: ["Core", "Hip Flexors"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Knees-to-Chest Pose (Apanasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Sphinx Pose (Salamba Bhujangasana)": TagAssignment(groups: ["Core", "Back"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Hero Pose (Virasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Revolved Triangle Pose (Parivrtta Trikonasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga"]),
            "Revolved Side Angle Pose (Parivrtta Parsvakonasana)": TagAssignment(groups: ["Core", "Legs"], categories: ["Bodyweight"], workouts: ["Yoga"]),
            "Legs Up the Wall Pose (Viparita Karani)": TagAssignment(groups: ["Legs"], categories: ["Bodyweight"], workouts: ["Recovery", "Yoga"]),
            "Four-Limbed Staff Pose (Chaturanga)": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Sun Salutation A (Surya Namaskar A)": TagAssignment(groups: ["Core", "Full Body"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Sun Salutation B (Surya Namaskar B)": TagAssignment(groups: ["Core", "Full Body"], categories: ["Bodyweight"], workouts: ["Yoga", "Full Body"]),
            "Eight-Angle Pose (Astavakrasana)": TagAssignment(groups: ["Core", "Arms"], categories: ["Bodyweight"], workouts: ["Yoga"]),
            "Shoulder Stand (Sarvangasana)": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Plow Pose (Halasana)": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Yoga", "Recovery"]),
            "Headstand (Sirsasana)": TagAssignment(groups: ["Core", "Shoulders"], categories: ["Bodyweight"], workouts: ["Yoga"])

        
        
        ]

        // ============================
        // Insert pivot records
        // ============================
        for (exerciseName, assignment) in assignments {

            guard let exerciseId = exerciseMap[exerciseName] else {
                fatalError("❌ Exercise not found: \(exerciseName)")
            }

            try insert(db, exerciseId, assignment.groups, "Group", tagMap)
            try insert(db, exerciseId, assignment.categories, "Category", tagMap)
            try insert(db, exerciseId, assignment.workouts, "Workout", tagMap)
        }

        print("🔗 Seeded exercise_tag_pivots table.")
    }

    private static func insert(
        _ db: Database,
        _ exerciseId: Int,
        _ tagNames: [String],
        _ type: String,
        _ tagMap: [String: Int]
    ) throws {

        guard !tagNames.isEmpty else {
            fatalError("❌ No \(type) tag for exercise_id \(exerciseId)")
        }

        guard tagNames.count <= 2 else {
            fatalError("❌ \(type) must have at most 2 tags")
        }

        for name in tagNames {
            let key = "\(type)|\(name)"
            guard let tagId = tagMap[key] else {
                fatalError("❌ Missing tag for pivot — type=\(type) name=\(name). Ensure ExerciseTagSeeder created a tag with key: \(key)")
            }

            try db.execute(
                sql: """
                INSERT INTO exercise_tag_pivots
                (exercise_id, exercise_tag_id, created_at, updated_at)
                VALUES (?, ?, ?, ?)
                """,
                arguments: [exerciseId, tagId, Date(), Date()]
            )
        }
    }
}

